/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PreviewTokenRouteImport } from './routes/preview/$token'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClient_idLayoutRouteImport } from './routes/_app/clients/$client_id/layout'
import { Route as AppProcessesIndexRouteImport } from './routes/_app/processes/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AuthActivateTokenRouteImport } from './routes/_auth/activate/$token'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AppClientsClient_idIndexRouteImport } from './routes/_app/clients/$client_id/index'
import { Route as AppProcessesProcess_idIndexRouteImport } from './routes/_app/processes/$process_id/index'
import { Route as AppClientsClient_idCompaniesCompany_idLayoutRouteImport } from './routes/_app/clients/$client_id/companies/$company_id/layout'
import { Route as AppClientsClient_idFilesIndexRouteImport } from './routes/_app/clients/$client_id/files/index'
import { Route as AppClientsClient_idIntakesIndexRouteImport } from './routes/_app/clients/$client_id/intakes/index'
import { Route as AppClientsClient_idTemplatesIndexRouteImport } from './routes/_app/clients/$client_id/templates/index'
import { Route as AppClientsClient_idTemplatesTemplate_idRouteImport } from './routes/_app/clients/$client_id/templates/$template_id'
import { Route as AppClientsClient_idCompaniesCompany_idIndexRouteImport } from './routes/_app/clients/$client_id/companies/$company_id/index'
import { Route as AppClientsClient_idCompaniesCompany_idFilesIndexRouteImport } from './routes/_app/clients/$client_id/companies/$company_id/files/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsClient_idLayoutRoute =
  AppClientsClient_idLayoutRouteImport.update({
    id: '/clients/$client_id',
    path: '/clients/$client_id',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppProcessesIndexRoute = AppProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthActivateTokenRoute = AuthActivateTokenRouteImport.update({
  id: '/_auth/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsClient_idIndexRoute =
  AppClientsClient_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppProcessesProcess_idIndexRoute =
  AppProcessesProcess_idIndexRouteImport.update({
    id: '/processes/$process_id/',
    path: '/processes/$process_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppClientsClient_idCompaniesCompany_idLayoutRoute =
  AppClientsClient_idCompaniesCompany_idLayoutRouteImport.update({
    id: '/companies/$company_id',
    path: '/companies/$company_id',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idFilesIndexRoute =
  AppClientsClient_idFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idIntakesIndexRoute =
  AppClientsClient_idIntakesIndexRouteImport.update({
    id: '/intakes/',
    path: '/intakes/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idTemplatesIndexRoute =
  AppClientsClient_idTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idTemplatesTemplate_idRoute =
  AppClientsClient_idTemplatesTemplate_idRouteImport.update({
    id: '/templates/$template_id',
    path: '/templates/$template_id',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idCompaniesCompany_idIndexRoute =
  AppClientsClient_idCompaniesCompany_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppClientsClient_idCompaniesCompany_idLayoutRoute,
  } as any)
const AppClientsClient_idCompaniesCompany_idFilesIndexRoute =
  AppClientsClient_idCompaniesCompany_idFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AppClientsClient_idCompaniesCompany_idLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/clients/$client_id': typeof AppClientsClient_idLayoutRouteWithChildren
  '/activate/$token': typeof AuthActivateTokenRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/processes/': typeof AppProcessesIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/clients/$client_id/': typeof AppClientsClient_idIndexRoute
  '/processes/$process_id/': typeof AppProcessesProcess_idIndexRoute
  '/clients/$client_id/companies/$company_id': typeof AppClientsClient_idCompaniesCompany_idLayoutRouteWithChildren
  '/clients/$client_id/templates/$template_id': typeof AppClientsClient_idTemplatesTemplate_idRoute
  '/clients/$client_id/files/': typeof AppClientsClient_idFilesIndexRoute
  '/clients/$client_id/intakes/': typeof AppClientsClient_idIntakesIndexRoute
  '/clients/$client_id/templates/': typeof AppClientsClient_idTemplatesIndexRoute
  '/clients/$client_id/companies/$company_id/': typeof AppClientsClient_idCompaniesCompany_idIndexRoute
  '/clients/$client_id/companies/$company_id/files/': typeof AppClientsClient_idCompaniesCompany_idFilesIndexRoute
}
export interface FileRoutesByTo {
  '/preview/$token': typeof PreviewTokenRoute
  '/': typeof AppIndexRoute
  '/activate/$token': typeof AuthActivateTokenRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/processes': typeof AppProcessesIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/clients/$client_id': typeof AppClientsClient_idIndexRoute
  '/processes/$process_id': typeof AppProcessesProcess_idIndexRoute
  '/clients/$client_id/templates/$template_id': typeof AppClientsClient_idTemplatesTemplate_idRoute
  '/clients/$client_id/files': typeof AppClientsClient_idFilesIndexRoute
  '/clients/$client_id/intakes': typeof AppClientsClient_idIntakesIndexRoute
  '/clients/$client_id/templates': typeof AppClientsClient_idTemplatesIndexRoute
  '/clients/$client_id/companies/$company_id': typeof AppClientsClient_idCompaniesCompany_idIndexRoute
  '/clients/$client_id/companies/$company_id/files': typeof AppClientsClient_idCompaniesCompany_idFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/preview/$token': typeof PreviewTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$client_id': typeof AppClientsClient_idLayoutRouteWithChildren
  '/_auth/activate/$token': typeof AuthActivateTokenRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/processes/': typeof AppProcessesIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_app/clients/$client_id/': typeof AppClientsClient_idIndexRoute
  '/_app/processes/$process_id/': typeof AppProcessesProcess_idIndexRoute
  '/_app/clients/$client_id/companies/$company_id': typeof AppClientsClient_idCompaniesCompany_idLayoutRouteWithChildren
  '/_app/clients/$client_id/templates/$template_id': typeof AppClientsClient_idTemplatesTemplate_idRoute
  '/_app/clients/$client_id/files/': typeof AppClientsClient_idFilesIndexRoute
  '/_app/clients/$client_id/intakes/': typeof AppClientsClient_idIntakesIndexRoute
  '/_app/clients/$client_id/templates/': typeof AppClientsClient_idTemplatesIndexRoute
  '/_app/clients/$client_id/companies/$company_id/': typeof AppClientsClient_idCompaniesCompany_idIndexRoute
  '/_app/clients/$client_id/companies/$company_id/files/': typeof AppClientsClient_idCompaniesCompany_idFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/$token'
    | '/clients/$client_id'
    | '/activate/$token'
    | '/calendar/'
    | '/clients/'
    | '/processes/'
    | '/tasks/'
    | '/users/'
    | '/sign-in/'
    | '/clients/$client_id/'
    | '/processes/$process_id/'
    | '/clients/$client_id/companies/$company_id'
    | '/clients/$client_id/templates/$template_id'
    | '/clients/$client_id/files/'
    | '/clients/$client_id/intakes/'
    | '/clients/$client_id/templates/'
    | '/clients/$client_id/companies/$company_id/'
    | '/clients/$client_id/companies/$company_id/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preview/$token'
    | '/'
    | '/activate/$token'
    | '/calendar'
    | '/clients'
    | '/processes'
    | '/tasks'
    | '/users'
    | '/sign-in'
    | '/clients/$client_id'
    | '/processes/$process_id'
    | '/clients/$client_id/templates/$template_id'
    | '/clients/$client_id/files'
    | '/clients/$client_id/intakes'
    | '/clients/$client_id/templates'
    | '/clients/$client_id/companies/$company_id'
    | '/clients/$client_id/companies/$company_id/files'
  id:
    | '__root__'
    | '/_app'
    | '/preview/$token'
    | '/_app/'
    | '/_app/clients/$client_id'
    | '/_auth/activate/$token'
    | '/_app/calendar/'
    | '/_app/clients/'
    | '/_app/processes/'
    | '/_app/tasks/'
    | '/_app/users/'
    | '/_auth/sign-in/'
    | '/_app/clients/$client_id/'
    | '/_app/processes/$process_id/'
    | '/_app/clients/$client_id/companies/$company_id'
    | '/_app/clients/$client_id/templates/$template_id'
    | '/_app/clients/$client_id/files/'
    | '/_app/clients/$client_id/intakes/'
    | '/_app/clients/$client_id/templates/'
    | '/_app/clients/$client_id/companies/$company_id/'
    | '/_app/clients/$client_id/companies/$company_id/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  PreviewTokenRoute: typeof PreviewTokenRoute
  AuthActivateTokenRoute: typeof AuthActivateTokenRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/$client_id': {
      id: '/_app/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/clients/$client_id'
      preLoaderRoute: typeof AppClientsClient_idLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/processes/': {
      id: '/_app/processes/'
      path: '/processes'
      fullPath: '/processes/'
      preLoaderRoute: typeof AppProcessesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/activate/$token': {
      id: '/_auth/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof AuthActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/$client_id/': {
      id: '/_app/clients/$client_id/'
      path: '/'
      fullPath: '/clients/$client_id/'
      preLoaderRoute: typeof AppClientsClient_idIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/processes/$process_id/': {
      id: '/_app/processes/$process_id/'
      path: '/processes/$process_id'
      fullPath: '/processes/$process_id/'
      preLoaderRoute: typeof AppProcessesProcess_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/$client_id/companies/$company_id': {
      id: '/_app/clients/$client_id/companies/$company_id'
      path: '/companies/$company_id'
      fullPath: '/clients/$client_id/companies/$company_id'
      preLoaderRoute: typeof AppClientsClient_idCompaniesCompany_idLayoutRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/files/': {
      id: '/_app/clients/$client_id/files/'
      path: '/files'
      fullPath: '/clients/$client_id/files/'
      preLoaderRoute: typeof AppClientsClient_idFilesIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/intakes/': {
      id: '/_app/clients/$client_id/intakes/'
      path: '/intakes'
      fullPath: '/clients/$client_id/intakes/'
      preLoaderRoute: typeof AppClientsClient_idIntakesIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/templates/': {
      id: '/_app/clients/$client_id/templates/'
      path: '/templates'
      fullPath: '/clients/$client_id/templates/'
      preLoaderRoute: typeof AppClientsClient_idTemplatesIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/templates/$template_id': {
      id: '/_app/clients/$client_id/templates/$template_id'
      path: '/templates/$template_id'
      fullPath: '/clients/$client_id/templates/$template_id'
      preLoaderRoute: typeof AppClientsClient_idTemplatesTemplate_idRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/companies/$company_id/': {
      id: '/_app/clients/$client_id/companies/$company_id/'
      path: '/'
      fullPath: '/clients/$client_id/companies/$company_id/'
      preLoaderRoute: typeof AppClientsClient_idCompaniesCompany_idIndexRouteImport
      parentRoute: typeof AppClientsClient_idCompaniesCompany_idLayoutRoute
    }
    '/_app/clients/$client_id/companies/$company_id/files/': {
      id: '/_app/clients/$client_id/companies/$company_id/files/'
      path: '/files'
      fullPath: '/clients/$client_id/companies/$company_id/files/'
      preLoaderRoute: typeof AppClientsClient_idCompaniesCompany_idFilesIndexRouteImport
      parentRoute: typeof AppClientsClient_idCompaniesCompany_idLayoutRoute
    }
  }
}

interface AppClientsClient_idCompaniesCompany_idLayoutRouteChildren {
  AppClientsClient_idCompaniesCompany_idIndexRoute: typeof AppClientsClient_idCompaniesCompany_idIndexRoute
  AppClientsClient_idCompaniesCompany_idFilesIndexRoute: typeof AppClientsClient_idCompaniesCompany_idFilesIndexRoute
}

const AppClientsClient_idCompaniesCompany_idLayoutRouteChildren: AppClientsClient_idCompaniesCompany_idLayoutRouteChildren =
  {
    AppClientsClient_idCompaniesCompany_idIndexRoute:
      AppClientsClient_idCompaniesCompany_idIndexRoute,
    AppClientsClient_idCompaniesCompany_idFilesIndexRoute:
      AppClientsClient_idCompaniesCompany_idFilesIndexRoute,
  }

const AppClientsClient_idCompaniesCompany_idLayoutRouteWithChildren =
  AppClientsClient_idCompaniesCompany_idLayoutRoute._addFileChildren(
    AppClientsClient_idCompaniesCompany_idLayoutRouteChildren,
  )

interface AppClientsClient_idLayoutRouteChildren {
  AppClientsClient_idIndexRoute: typeof AppClientsClient_idIndexRoute
  AppClientsClient_idCompaniesCompany_idLayoutRoute: typeof AppClientsClient_idCompaniesCompany_idLayoutRouteWithChildren
  AppClientsClient_idTemplatesTemplate_idRoute: typeof AppClientsClient_idTemplatesTemplate_idRoute
  AppClientsClient_idFilesIndexRoute: typeof AppClientsClient_idFilesIndexRoute
  AppClientsClient_idIntakesIndexRoute: typeof AppClientsClient_idIntakesIndexRoute
  AppClientsClient_idTemplatesIndexRoute: typeof AppClientsClient_idTemplatesIndexRoute
}

const AppClientsClient_idLayoutRouteChildren: AppClientsClient_idLayoutRouteChildren =
  {
    AppClientsClient_idIndexRoute: AppClientsClient_idIndexRoute,
    AppClientsClient_idCompaniesCompany_idLayoutRoute:
      AppClientsClient_idCompaniesCompany_idLayoutRouteWithChildren,
    AppClientsClient_idTemplatesTemplate_idRoute:
      AppClientsClient_idTemplatesTemplate_idRoute,
    AppClientsClient_idFilesIndexRoute: AppClientsClient_idFilesIndexRoute,
    AppClientsClient_idIntakesIndexRoute: AppClientsClient_idIntakesIndexRoute,
    AppClientsClient_idTemplatesIndexRoute:
      AppClientsClient_idTemplatesIndexRoute,
  }

const AppClientsClient_idLayoutRouteWithChildren =
  AppClientsClient_idLayoutRoute._addFileChildren(
    AppClientsClient_idLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClient_idLayoutRoute: typeof AppClientsClient_idLayoutRouteWithChildren
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppProcessesIndexRoute: typeof AppProcessesIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppProcessesProcess_idIndexRoute: typeof AppProcessesProcess_idIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientsClient_idLayoutRoute: AppClientsClient_idLayoutRouteWithChildren,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppProcessesIndexRoute: AppProcessesIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppProcessesProcess_idIndexRoute: AppProcessesProcess_idIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  PreviewTokenRoute: PreviewTokenRoute,
  AuthActivateTokenRoute: AuthActivateTokenRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
