/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PreviewTokenRouteImport } from './routes/preview/$token'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClient_idLayoutRouteImport } from './routes/_app/clients/$client_id/layout'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AuthActivateTokenRouteImport } from './routes/_auth/activate/$token'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AppClientsClient_idIndexRouteImport } from './routes/_app/clients/$client_id/index'
import { Route as AppClientsClient_idFilesIndexRouteImport } from './routes/_app/clients/$client_id/files/index'
import { Route as AppClientsClient_idIntakesIndexRouteImport } from './routes/_app/clients/$client_id/intakes/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppClientsClient_idLayoutRoute =
  AppClientsClient_idLayoutRouteImport.update({
    id: '/clients/$client_id',
    path: '/clients/$client_id',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthActivateTokenRoute = AuthActivateTokenRouteImport.update({
  id: '/_auth/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsClient_idIndexRoute =
  AppClientsClient_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idFilesIndexRoute =
  AppClientsClient_idFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)
const AppClientsClient_idIntakesIndexRoute =
  AppClientsClient_idIntakesIndexRouteImport.update({
    id: '/intakes/',
    path: '/intakes/',
    getParentRoute: () => AppClientsClient_idLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/clients/$client_id': typeof AppClientsClient_idLayoutRouteWithChildren
  '/activate/$token': typeof AuthActivateTokenRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/clients/$client_id/': typeof AppClientsClient_idIndexRoute
  '/clients/$client_id/files/': typeof AppClientsClient_idFilesIndexRoute
  '/clients/$client_id/intakes/': typeof AppClientsClient_idIntakesIndexRoute
}
export interface FileRoutesByTo {
  '/preview/$token': typeof PreviewTokenRoute
  '/': typeof AppIndexRoute
  '/activate/$token': typeof AuthActivateTokenRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/clients/$client_id': typeof AppClientsClient_idIndexRoute
  '/clients/$client_id/files': typeof AppClientsClient_idFilesIndexRoute
  '/clients/$client_id/intakes': typeof AppClientsClient_idIntakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/preview/$token': typeof PreviewTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$client_id': typeof AppClientsClient_idLayoutRouteWithChildren
  '/_auth/activate/$token': typeof AuthActivateTokenRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_app/clients/$client_id/': typeof AppClientsClient_idIndexRoute
  '/_app/clients/$client_id/files/': typeof AppClientsClient_idFilesIndexRoute
  '/_app/clients/$client_id/intakes/': typeof AppClientsClient_idIntakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/$token'
    | '/clients/$client_id'
    | '/activate/$token'
    | '/calendar/'
    | '/clients/'
    | '/tasks/'
    | '/sign-in/'
    | '/clients/$client_id/'
    | '/clients/$client_id/files/'
    | '/clients/$client_id/intakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preview/$token'
    | '/'
    | '/activate/$token'
    | '/calendar'
    | '/clients'
    | '/tasks'
    | '/sign-in'
    | '/clients/$client_id'
    | '/clients/$client_id/files'
    | '/clients/$client_id/intakes'
  id:
    | '__root__'
    | '/_app'
    | '/preview/$token'
    | '/_app/'
    | '/_app/clients/$client_id'
    | '/_auth/activate/$token'
    | '/_app/calendar/'
    | '/_app/clients/'
    | '/_app/tasks/'
    | '/_auth/sign-in/'
    | '/_app/clients/$client_id/'
    | '/_app/clients/$client_id/files/'
    | '/_app/clients/$client_id/intakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  PreviewTokenRoute: typeof PreviewTokenRoute
  AuthActivateTokenRoute: typeof AuthActivateTokenRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/clients/$client_id': {
      id: '/_app/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/clients/$client_id'
      preLoaderRoute: typeof AppClientsClient_idLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/activate/$token': {
      id: '/_auth/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof AuthActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/$client_id/': {
      id: '/_app/clients/$client_id/'
      path: '/'
      fullPath: '/clients/$client_id/'
      preLoaderRoute: typeof AppClientsClient_idIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/files/': {
      id: '/_app/clients/$client_id/files/'
      path: '/files'
      fullPath: '/clients/$client_id/files/'
      preLoaderRoute: typeof AppClientsClient_idFilesIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
    '/_app/clients/$client_id/intakes/': {
      id: '/_app/clients/$client_id/intakes/'
      path: '/intakes'
      fullPath: '/clients/$client_id/intakes/'
      preLoaderRoute: typeof AppClientsClient_idIntakesIndexRouteImport
      parentRoute: typeof AppClientsClient_idLayoutRoute
    }
  }
}

interface AppClientsClient_idLayoutRouteChildren {
  AppClientsClient_idIndexRoute: typeof AppClientsClient_idIndexRoute
  AppClientsClient_idFilesIndexRoute: typeof AppClientsClient_idFilesIndexRoute
  AppClientsClient_idIntakesIndexRoute: typeof AppClientsClient_idIntakesIndexRoute
}

const AppClientsClient_idLayoutRouteChildren: AppClientsClient_idLayoutRouteChildren =
  {
    AppClientsClient_idIndexRoute: AppClientsClient_idIndexRoute,
    AppClientsClient_idFilesIndexRoute: AppClientsClient_idFilesIndexRoute,
    AppClientsClient_idIntakesIndexRoute: AppClientsClient_idIntakesIndexRoute,
  }

const AppClientsClient_idLayoutRouteWithChildren =
  AppClientsClient_idLayoutRoute._addFileChildren(
    AppClientsClient_idLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClient_idLayoutRoute: typeof AppClientsClient_idLayoutRouteWithChildren
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientsClient_idLayoutRoute: AppClientsClient_idLayoutRouteWithChildren,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  PreviewTokenRoute: PreviewTokenRoute,
  AuthActivateTokenRoute: AuthActivateTokenRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
