/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const activateAccountStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.email(),
  role: z.enum(['ADMIN', 'MEMBER']),
  isActive: z.boolean(),
}).strict()

export const activateAccountResponseSchema = activateAccountStatus200Schema

export const activateAccountBodySchema = z.object({
  token: z.string().min(1),
})