/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createIntakePreviewLinkPathIdSchema = z.string()

export const createIntakePreviewLinkStatus201Schema = z.object({
  token: z.string(),
  url: z.string(),
}).strict()

export const createIntakePreviewLinkResponseSchema = createIntakePreviewLinkStatus201Schema