/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createEventStatus201Schema = z.object({
  id: z.string(),
}).strict()

export const createEventResponseSchema = createEventStatus201Schema

export const createEventBodySchema = z.object({
  title: z.string().min(1).max(180),
  description: z.string().max(2000).optional(),
  startAt: z.iso.datetime(),
  isGlobal: z.boolean().optional(),
  reminderMinutesBefore: z.int().min(0).max(10080).optional(),
})