/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createUserStatus201Schema = z.object({
  id: z.string(),
}).strict()

export const createUserResponseSchema = createUserStatus201Schema

export const createUserBodySchema = z.object({
  name: z.string().min(1).max(180),
  email: z.email(),
  role: z.enum(['ADMIN', 'MEMBER']),
})