/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createProcessMovementPathProcessIdSchema = z.string()

export const createProcessMovementStatus201Schema = z.object({
  id: z.string(),
}).strict()

export const createProcessMovementResponseSchema = createProcessMovementStatus201Schema

export const createProcessMovementBodySchema = z.object({
  description: z.string().min(1).max(2000),
  occurredAt: z.iso.date(),
})