/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createTaskStatus201Schema = z.object({
  id: z.string(),
}).strict()

export const createTaskResponseSchema = createTaskStatus201Schema

export const createTaskBodySchema = z.object({
  title: z.string().min(1).max(180),
  description: z.string().max(2000).optional(),
  dueDate: z.iso.date().optional(),
  status: z.enum(['TODO', 'IN_PROGRESS', 'DONE']).optional(),
})