/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteDocumentPathIdSchema = z.string()

export const deleteDocumentStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteDocumentResponseSchema = deleteDocumentStatus200Schema