/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteTaskPathIdSchema = z.string()

export const deleteTaskStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteTaskResponseSchema = deleteTaskStatus200Schema