/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteCompanyPathIdSchema = z.string()

export const deleteCompanyStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteCompanyResponseSchema = deleteCompanyStatus200Schema