/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteProcessPathIdSchema = z.string()

export const deleteProcessStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteProcessResponseSchema = deleteProcessStatus200Schema