/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteIntakePathIdSchema = z.string()

export const deleteIntakeStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteIntakeResponseSchema = deleteIntakeStatus200Schema