/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteEventPathIdSchema = z.string()

export const deleteEventStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const deleteEventResponseSchema = deleteEventStatus200Schema