/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const downloadDocumentPathIdSchema = z.string()

export const downloadDocumentStatus200Schema = z.any()

export const downloadDocumentResponseSchema = downloadDocumentStatus200Schema