/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getClientPathIdSchema = z.string()

export const getClientStatus200Schema = z.object({
  id: z.string(),
  fullName: z.string(),
  cpf: z.string(),
  rg: z.string().nullable(),
  birthDate: z.iso.date().nullable(),
  maritalStatus: z.string().nullable(),
  profession: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  isActive: z.boolean(),
  createdAt: z.iso.datetime(),
}).strict()

export const getClientResponseSchema = getClientStatus200Schema