/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getHealthStatus200Schema = z.any()

export const getHealthResponseSchema = getHealthStatus200Schema