/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getMeStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.email(),
  role: z.enum(['ADMIN', 'MEMBER']),
  isActive: z.boolean(),
}).strict()

export const getMeResponseSchema = getMeStatus200Schema