/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getOpenapiJsonStatus200Schema = z.any()

export const getOpenapiJsonResponseSchema = getOpenapiJsonStatus200Schema