/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getPublicPreviewQueryTokenSchema = z.string().min(1)

export const getPublicPreviewStatus200Schema = z.object({
  type: z.enum(['intake']),
  intake: z.object({
    id: z.string(),
    clientId: z.string(),
    practiceAreas: z.array(z.enum(['PREVIDENCIARIO', 'TRABALHISTA', 'CIVEL', 'FAMILIA', 'CONSUMIDOR', 'EMPRESARIAL', 'CONTRATOS', 'OUTRO'])),
    practiceAreaOther: z.string().nullable(),
    clientReport: z.string().nullable(),
    lawyerAnalysis: z.string().nullable(),
    nextSteps: z.array(z.enum(['SOLICITAR_DOCUMENTOS', 'ELABORAR_PARECER', 'AGENDAR_RETORNO', 'ELABORAR_CONTRATO', 'PROTOCOLAR_ACAO', 'TENTATIVA_ACORDO', 'OUTRO'])),
    nextStepsOther: z.string().nullable(),
    feeAmount: z.number().nullable(),
    paymentMethod: z.string().nullable(),
    referralSource: z.enum(['INDICACAO', 'INSTAGRAM', 'FACEBOOK', 'GOOGLE', 'SITE', 'OUTRO']).nullable(),
    referredByName: z.string().nullable(),
    referralSourceOther: z.string().nullable(),
    lgpdConsent: z.boolean(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    user: z.object({
      id: z.string(),
      name: z.string(),
    }).strict(),
  }).strict(),
  client: z.object({
    id: z.string(),
    personType: z.enum(['FISICA', 'JURIDICA']),
    fullName: z.string(),
    cpf: z.string().nullable(),
    rg: z.string().nullable(),
    birthDate: z.iso.date().nullable(),
    maritalStatus: z.string().nullable(),
    profession: z.string().nullable(),
    cnpj: z.string().nullable(),
    razaoSocial: z.string().nullable(),
    nomeFantasia: z.string().nullable(),
    phone: z.string().nullable(),
    email: z.string().nullable(),
    address: z.string().nullable(),
    isActive: z.boolean(),
    createdAt: z.iso.datetime(),
  }).strict(),
}).strict()

export const getPublicPreviewResponseSchema = getPublicPreviewStatus200Schema