/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getProcessPathIdSchema = z.string()

export const getProcessStatus200Schema = z.object({
  id: z.string(),
  caseNumber: z.string().nullable(),
  clientId: z.string(),
  plaintiff: z.string(),
  defendant: z.string(),
  notes: z.string().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  client: z.object({
    id: z.string(),
    fullName: z.string(),
  }).strict(),
  user: z.object({
    id: z.string(),
    name: z.string(),
  }).strict(),
}).strict()

export const getProcessResponseSchema = getProcessStatus200Schema