/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getTemplatePathIdSchema = z.string()

export const getTemplateStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  title: z.string(),
  content: z.object({
    blocks: z.array(z.union([
      z.object({
        type: z.enum(['paragraph']),
        text: z.string(),
        breakBefore: z.boolean().optional(),
      }).strict(),
      z.object({
        type: z.enum(['signature-line']),
        label: z.string().optional(),
        breakBefore: z.boolean().optional(),
      }).strict(),
    ])),
  }).strict(),
}).strict()

export const getTemplateResponseSchema = getTemplateStatus200Schema