/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listIntakesQueryPageSchema = z.int().min(1).max(9007199254740991).optional().default(1)

export const listIntakesQueryPageSizeSchema = z.int().min(1).max(100).optional().default(20)

export const listIntakesPathClientIdSchema = z.string()

export const listIntakesStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    clientId: z.string(),
    practiceAreas: z.array(z.enum(['PREVIDENCIARIO', 'TRABALHISTA', 'CIVEL', 'FAMILIA', 'CONSUMIDOR', 'EMPRESARIAL', 'CONTRATOS', 'OUTRO'])),
    practiceAreaOther: z.string().nullable(),
    clientReport: z.string().nullable(),
    lawyerAnalysis: z.string().nullable(),
    nextSteps: z.array(z.enum(['SOLICITAR_DOCUMENTOS', 'ELABORAR_PARECER', 'AGENDAR_RETORNO', 'ELABORAR_CONTRATO', 'PROTOCOLAR_ACAO', 'TENTATIVA_ACORDO', 'OUTRO'])),
    nextStepsOther: z.string().nullable(),
    feeAmount: z.number().nullable(),
    paymentMethod: z.string().nullable(),
    referralSource: z.enum(['INDICACAO', 'INSTAGRAM', 'FACEBOOK', 'GOOGLE', 'SITE', 'OUTRO']).nullable(),
    referredByName: z.string().nullable(),
    referralSourceOther: z.string().nullable(),
    lgpdConsent: z.boolean(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    user: z.object({
      id: z.string(),
      name: z.string(),
    }).strict(),
  }).strict()),
  pagination: z.object({
    page: z.number(),
    pageSize: z.number(),
    total: z.number(),
    pageCount: z.number(),
  }).strict(),
}).strict()

export const listIntakesResponseSchema = listIntakesStatus200Schema