/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listClientsQueryPageSchema = z.int().min(1).max(9007199254740991).optional().default(1)

export const listClientsQueryPageSizeSchema = z.int().min(1).max(100).optional().default(20)

export const listClientsQuerySearchSchema = z.string().min(1).optional()

export const listClientsQueryIsActiveSchema = z.enum(['true', 'false']).optional()

export const listClientsStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    personType: z.enum(['FISICA', 'JURIDICA']),
    fullName: z.string(),
    cpf: z.string().nullable(),
    rg: z.string().nullable(),
    birthDate: z.iso.date().nullable(),
    maritalStatus: z.string().nullable(),
    profession: z.string().nullable(),
    cnpj: z.string().nullable(),
    razaoSocial: z.string().nullable(),
    nomeFantasia: z.string().nullable(),
    phone: z.string().nullable(),
    email: z.string().nullable(),
    address: z.string().nullable(),
    isActive: z.boolean(),
    createdAt: z.iso.datetime(),
  }).strict()),
  pagination: z.object({
    page: z.number(),
    pageSize: z.number(),
    total: z.number(),
    pageCount: z.number(),
  }).strict(),
}).strict()

export const listClientsResponseSchema = listClientsStatus200Schema