/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listTemplatesStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
  }).strict()),
}).strict()

export const listTemplatesResponseSchema = listTemplatesStatus200Schema