/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listCompaniesPathClientIdSchema = z.string()

export const listCompaniesStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    cnpj: z.string(),
    razaoSocial: z.string(),
    nomeFantasia: z.string().nullable(),
    phone: z.string().nullable(),
    email: z.string().nullable(),
    address: z.string().nullable(),
    isActive: z.boolean(),
    legalRepresentativeId: z.string(),
    createdAt: z.iso.datetime(),
  }).strict()),
}).strict()

export const listCompaniesResponseSchema = listCompaniesStatus200Schema