/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listTasksStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    title: z.string(),
    description: z.string().nullable(),
    status: z.enum(['TODO', 'IN_PROGRESS', 'DONE']),
    position: z.number(),
    dueDate: z.iso.date().nullable(),
    createdAt: z.iso.datetime(),
  }).strict()),
}).strict()

export const listTasksResponseSchema = listTasksStatus200Schema