/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listProcessesQueryPageSchema = z.int().min(1).max(9007199254740991).optional().default(1)

export const listProcessesQueryPageSizeSchema = z.int().min(1).max(100).optional().default(20)

export const listProcessesStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    caseNumber: z.string().nullable(),
    clientId: z.string(),
    plaintiff: z.string(),
    defendant: z.string(),
    notes: z.string().nullable(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    client: z.object({
      id: z.string(),
      fullName: z.string(),
    }).strict(),
    user: z.object({
      id: z.string(),
      name: z.string(),
    }).strict(),
  }).strict()),
  pagination: z.object({
    page: z.number(),
    pageSize: z.number(),
    total: z.number(),
    pageCount: z.number(),
  }).strict(),
}).strict()

export const listProcessesResponseSchema = listProcessesStatus200Schema