/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listEventsQueryFromSchema = z.iso.datetime()

export const listEventsQueryToSchema = z.iso.datetime()

export const listEventsStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    userId: z.string(),
    title: z.string(),
    description: z.string().nullable(),
    startAt: z.iso.datetime(),
    isGlobal: z.boolean(),
    reminderMinutesBefore: z.number().nullable(),
    createdAt: z.iso.datetime(),
  }).strict()),
}).strict()

export const listEventsResponseSchema = listEventsStatus200Schema