/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listUsersStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    role: z.enum(['ADMIN', 'MEMBER']),
    isActive: z.boolean(),
    createdAt: z.iso.datetime(),
  }).strict()),
}).strict()

export const listUsersResponseSchema = listUsersStatus200Schema