/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listProcessMovementsPathProcessIdSchema = z.string()

export const listProcessMovementsStatus200Schema = z.object({
  data: z.array(z.object({
    id: z.string(),
    processId: z.string(),
    description: z.string(),
    occurredAt: z.iso.date(),
    createdAt: z.iso.datetime(),
  }).strict()),
}).strict()

export const listProcessMovementsResponseSchema = listProcessMovementsStatus200Schema