/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const moveTaskPathIdSchema = z.string()

export const moveTaskStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const moveTaskResponseSchema = moveTaskStatus200Schema

export const moveTaskBodySchema = z.object({
  status: z.enum(['TODO', 'IN_PROGRESS', 'DONE']),
  orderedIds: z.array(z.string()).min(1),
})