/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const sendIntakeEmailPathIdSchema = z.string()

export const sendIntakeEmailStatus200Schema = z.object({
  sentTo: z.string(),
}).strict()

export const sendIntakeEmailResponseSchema = sendIntakeEmailStatus200Schema