/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const signInStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.email(),
  role: z.enum(['ADMIN', 'MEMBER']),
  isActive: z.boolean(),
}).strict()

export const signInResponseSchema = signInStatus200Schema

export const signInBodySchema = z.object({
  email: z.email(),
  password: z.string().min(1),
})