/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateIntakePathIdSchema = z.string()

export const updateIntakeStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const updateIntakeResponseSchema = updateIntakeStatus200Schema

export const updateIntakeBodySchema = z.object({
  practiceAreas: z.array(z.enum(['PREVIDENCIARIO', 'TRABALHISTA', 'CIVEL', 'FAMILIA', 'CONSUMIDOR', 'EMPRESARIAL', 'CONTRATOS', 'OUTRO'])).optional().default([]),
  practiceAreaOther: z.string().max(120).optional(),
  clientReport: z.string().max(5000).optional(),
  lawyerAnalysis: z.string().max(5000).optional(),
  nextSteps: z.array(z.enum(['SOLICITAR_DOCUMENTOS', 'ELABORAR_PARECER', 'AGENDAR_RETORNO', 'ELABORAR_CONTRATO', 'PROTOCOLAR_ACAO', 'TENTATIVA_ACORDO', 'OUTRO'])).optional().default([]),
  nextStepsOther: z.string().max(120).optional(),
  feeAmount: z.number().min(0).optional(),
  paymentMethod: z.string().max(60).optional(),
  referralSource: z.enum(['INDICACAO', 'INSTAGRAM', 'FACEBOOK', 'GOOGLE', 'SITE', 'OUTRO']).optional(),
  referredByName: z.string().max(120).optional(),
  referralSourceOther: z.string().max(120).optional(),
  lgpdConsent: z.boolean().optional().default(false),
})