/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateProcessPathIdSchema = z.string()

export const updateProcessStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const updateProcessResponseSchema = updateProcessStatus200Schema

export const updateProcessBodySchema = z.object({
  caseNumber: z.string().max(30).optional(),
  clientId: z.string(),
  plaintiff: z.string().min(1),
  defendant: z.string().min(1),
  notes: z.string().max(5000).optional(),
})