/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateCompanyPathIdSchema = z.string()

export const updateCompanyStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const updateCompanyResponseSchema = updateCompanyStatus200Schema

export const updateCompanyBodySchema = z.object({
  cnpj: z.string().min(14).max(18),
  razaoSocial: z.string().min(1).max(180),
  nomeFantasia: z.string().max(180).optional(),
  phone: z.string().max(30).optional(),
  email: z.email().optional(),
  address: z.string().max(255).optional(),
  isActive: z.boolean().optional(),
})