/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateClientPathIdSchema = z.string()

export const updateClientStatus200Schema = z.object({
  id: z.string(),
  fullName: z.string(),
  cpf: z.string(),
}).strict()

export const updateClientResponseSchema = updateClientStatus200Schema

export const updateClientBodySchema = z.object({
  fullName: z.string().min(1).max(180),
  cpf: z.string().min(11).max(14),
  rg: z.string().max(20).optional(),
  birthDate: z.iso.date().optional(),
  maritalStatus: z.string().max(60).optional(),
  profession: z.string().max(120).optional(),
  phone: z.string().max(30).optional(),
  email: z.email().optional(),
  address: z.string().max(255).optional(),
  isActive: z.boolean().optional(),
})