/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateTaskPathIdSchema = z.string()

export const updateTaskStatus200Schema = z.object({
  id: z.string(),
}).strict()

export const updateTaskResponseSchema = updateTaskStatus200Schema

export const updateTaskBodySchema = z.object({
  title: z.string().min(1).max(180).optional(),
  description: z.string().max(2000).optional(),
  dueDate: z.iso.date().optional(),
})