/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const uploadDocumentPathClientIdSchema = z.string()

export const uploadDocumentStatus201Schema = z.object({
  id: z.string(),
  clientId: z.string(),
  originalName: z.string(),
  mimeType: z.string(),
  size: z.number(),
  createdAt: z.iso.datetime(),
}).strict()

export const uploadDocumentResponseSchema = uploadDocumentStatus201Schema