/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ActivateAccountOptions, ActivateAccountResponses } from '../types/ActivateAccount'
import { client } from '../.kubb/client'

/**
 * @summary Ativar conta a partir do link enviado por e-mail
 * {@link /auth/activate}
 */
export function activateAccount<ThrowOnError extends boolean = true>(options: Options<ActivateAccountOptions, ThrowOnError>): Promise<RequestResult<ActivateAccountResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/auth/activate', ...config }) as Promise<RequestResult<ActivateAccountResponses, ThrowOnError>>
}