/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateUserOptions, CreateUserResponses } from '../types/CreateUser'
import { client } from '../.kubb/client'

/**
 * @summary Cadastrar usuário
 * {@link /users}
 */
export function createUser<ThrowOnError extends boolean = true>(options: Options<CreateUserOptions, ThrowOnError>): Promise<RequestResult<CreateUserResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/users', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateUserResponses, ThrowOnError>>
}