/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateEventOptions, CreateEventResponses } from '../types/CreateEvent'
import { client } from '../.kubb/client'

/**
 * @summary Criar evento
 * {@link /events}
 */
export function createEvent<ThrowOnError extends boolean = true>(options: Options<CreateEventOptions, ThrowOnError>): Promise<RequestResult<CreateEventResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/events', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateEventResponses, ThrowOnError>>
}