/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateClientOptions, CreateClientResponses } from '../types/CreateClient'
import { client } from '../.kubb/client'

/**
 * @summary Criar cliente
 * {@link /clients}
 */
export function createClient<ThrowOnError extends boolean = true>(options: Options<CreateClientOptions, ThrowOnError>): Promise<RequestResult<CreateClientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/clients', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateClientResponses, ThrowOnError>>
}