/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateIntakePreviewLinkOptions, CreateIntakePreviewLinkResponses } from '../types/CreateIntakePreviewLink'
import { client } from '../.kubb/client'

/**
 * @summary Gerar link público de visualização do atendimento
 * {@link /intakes/:id/preview-link}
 */
export function createIntakePreviewLink<ThrowOnError extends boolean = true>(options: Options<CreateIntakePreviewLinkOptions, ThrowOnError>): Promise<RequestResult<CreateIntakePreviewLinkResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/intakes/{id}/preview-link', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateIntakePreviewLinkResponses, ThrowOnError>>
}