/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateCompanyOptions, CreateCompanyResponses } from '../types/CreateCompany'
import { client } from '../.kubb/client'

/**
 * @summary Cadastrar empresa representada pelo cliente
 * {@link /clients/:clientId/companies}
 */
export function createCompany<ThrowOnError extends boolean = true>(options: Options<CreateCompanyOptions, ThrowOnError>): Promise<RequestResult<CreateCompanyResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/clients/{clientId}/companies', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateCompanyResponses, ThrowOnError>>
}