/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateTaskOptions, CreateTaskResponses } from '../types/CreateTask'
import { client } from '../.kubb/client'

/**
 * @summary Criar tarefa
 * {@link /tasks}
 */
export function createTask<ThrowOnError extends boolean = true>(options: Options<CreateTaskOptions, ThrowOnError>): Promise<RequestResult<CreateTaskResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/tasks', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateTaskResponses, ThrowOnError>>
}