/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateIntakeOptions, CreateIntakeResponses } from '../types/CreateIntake'
import { client } from '../.kubb/client'

/**
 * @summary Criar atendimento
 * {@link /clients/:clientId/intakes}
 */
export function createIntake<ThrowOnError extends boolean = true>(options: Options<CreateIntakeOptions, ThrowOnError>): Promise<RequestResult<CreateIntakeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/clients/{clientId}/intakes', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateIntakeResponses, ThrowOnError>>
}