/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateProcessOptions, CreateProcessResponses } from '../types/CreateProcess'
import { client } from '../.kubb/client'

/**
 * @summary Criar processo
 * {@link /processes}
 */
export function createProcess<ThrowOnError extends boolean = true>(options: Options<CreateProcessOptions, ThrowOnError>): Promise<RequestResult<CreateProcessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/processes', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateProcessResponses, ThrowOnError>>
}