/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateProcessMovementOptions, CreateProcessMovementResponses } from '../types/CreateProcessMovement'
import { client } from '../.kubb/client'

/**
 * @summary Criar movimentação do processo
 * {@link /processes/:processId/movements}
 */
export function createProcessMovement<ThrowOnError extends boolean = true>(options: Options<CreateProcessMovementOptions, ThrowOnError>): Promise<RequestResult<CreateProcessMovementResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/processes/{processId}/movements', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<CreateProcessMovementResponses, ThrowOnError>>
}