/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteDocumentOptions, DeleteDocumentResponses } from '../types/DeleteDocument'
import { client } from '../.kubb/client'

/**
 * @summary Excluir documento
 * {@link /documents/:id}
 */
export function deleteDocument<ThrowOnError extends boolean = true>(options: Options<DeleteDocumentOptions, ThrowOnError>): Promise<RequestResult<DeleteDocumentResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/documents/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteDocumentResponses, ThrowOnError>>
}