/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteTaskOptions, DeleteTaskResponses } from '../types/DeleteTask'
import { client } from '../.kubb/client'

/**
 * @summary Excluir tarefa
 * {@link /tasks/:id}
 */
export function deleteTask<ThrowOnError extends boolean = true>(options: Options<DeleteTaskOptions, ThrowOnError>): Promise<RequestResult<DeleteTaskResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/tasks/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteTaskResponses, ThrowOnError>>
}