/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteProcessOptions, DeleteProcessResponses } from '../types/DeleteProcess'
import { client } from '../.kubb/client'

/**
 * @summary Excluir processo
 * {@link /processes/:id}
 */
export function deleteProcess<ThrowOnError extends boolean = true>(options: Options<DeleteProcessOptions, ThrowOnError>): Promise<RequestResult<DeleteProcessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/processes/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteProcessResponses, ThrowOnError>>
}