/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteCompanyOptions, DeleteCompanyResponses } from '../types/DeleteCompany'
import { client } from '../.kubb/client'

/**
 * @summary Excluir empresa
 * {@link /companies/:id}
 */
export function deleteCompany<ThrowOnError extends boolean = true>(options: Options<DeleteCompanyOptions, ThrowOnError>): Promise<RequestResult<DeleteCompanyResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/companies/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteCompanyResponses, ThrowOnError>>
}