/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteIntakeOptions, DeleteIntakeResponses } from '../types/DeleteIntake'
import { client } from '../.kubb/client'

/**
 * @summary Excluir atendimento
 * {@link /intakes/:id}
 */
export function deleteIntake<ThrowOnError extends boolean = true>(options: Options<DeleteIntakeOptions, ThrowOnError>): Promise<RequestResult<DeleteIntakeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/intakes/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteIntakeResponses, ThrowOnError>>
}