/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteEventOptions, DeleteEventResponses } from '../types/DeleteEvent'
import { client } from '../.kubb/client'

/**
 * @summary Excluir evento
 * {@link /events/:id}
 */
export function deleteEvent<ThrowOnError extends boolean = true>(options: Options<DeleteEventOptions, ThrowOnError>): Promise<RequestResult<DeleteEventResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/events/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DeleteEventResponses, ThrowOnError>>
}