/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DownloadDocumentOptions, DownloadDocumentResponses } from '../types/DownloadDocument'
import { client } from '../.kubb/client'

/**
 * @summary Baixar documento
 * {@link /documents/:id/download}
 */
export function downloadDocument<ThrowOnError extends boolean = true>(options: Options<DownloadDocumentOptions, ThrowOnError>): Promise<RequestResult<DownloadDocumentResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/documents/{id}/download', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<DownloadDocumentResponses, ThrowOnError>>
}