/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetCompanyOptions, GetCompanyResponses } from '../types/GetCompany'
import { client } from '../.kubb/client'

/**
 * @summary Buscar empresa
 * {@link /companies/:id}
 */
export function getCompany<ThrowOnError extends boolean = true>(options: Options<GetCompanyOptions, ThrowOnError>): Promise<RequestResult<GetCompanyResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/companies/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<GetCompanyResponses, ThrowOnError>>
}