/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetClientOptions, GetClientResponses } from '../types/GetClient'
import { client } from '../.kubb/client'

/**
 * @summary Buscar cliente
 * {@link /clients/:id}
 */
export function getClient<ThrowOnError extends boolean = true>(options: Options<GetClientOptions, ThrowOnError>): Promise<RequestResult<GetClientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/clients/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<GetClientResponses, ThrowOnError>>
}