/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetHealthOptions, GetHealthResponses } from '../types/GetHealth'
import { client } from '../.kubb/client'

/**
 * {@link /health}
 */
export function getHealth<ThrowOnError extends boolean = true>(options: Options<GetHealthOptions, ThrowOnError> = {}): Promise<RequestResult<GetHealthResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/health', ...config }) as Promise<RequestResult<GetHealthResponses, ThrowOnError>>
}