/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetMeOptions, GetMeResponses } from '../types/GetMe'
import { client } from '../.kubb/client'

/**
 * @summary Buscar usuário autenticado
 * {@link /auth/me}
 */
export function getMe<ThrowOnError extends boolean = true>(options: Options<GetMeOptions, ThrowOnError> = {}): Promise<RequestResult<GetMeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/auth/me', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<GetMeResponses, ThrowOnError>>
}