/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetOpenapiJsonOptions, GetOpenapiJsonResponses } from '../types/GetOpenapiJson'
import { client } from '../.kubb/client'

/**
 * {@link /openapi.json}
 */
export function getOpenapiJson<ThrowOnError extends boolean = true>(options: Options<GetOpenapiJsonOptions, ThrowOnError> = {}): Promise<RequestResult<GetOpenapiJsonResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/openapi.json', ...config }) as Promise<RequestResult<GetOpenapiJsonResponses, ThrowOnError>>
}