/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetProcessOptions, GetProcessResponses } from '../types/GetProcess'
import { client } from '../.kubb/client'

/**
 * @summary Buscar processo
 * {@link /processes/:id}
 */
export function getProcess<ThrowOnError extends boolean = true>(options: Options<GetProcessOptions, ThrowOnError>): Promise<RequestResult<GetProcessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/processes/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<GetProcessResponses, ThrowOnError>>
}