/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetPublicPreviewOptions, GetPublicPreviewResponses } from '../types/GetPublicPreview'
import { client } from '../.kubb/client'

/**
 * @summary Buscar um documento compartilhado publicamente
 * {@link /public/preview}
 */
export function getPublicPreview<ThrowOnError extends boolean = true>(options: Options<GetPublicPreviewOptions, ThrowOnError>): Promise<RequestResult<GetPublicPreviewResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/public/preview', ...config }) as Promise<RequestResult<GetPublicPreviewResponses, ThrowOnError>>
}