/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetTemplateOptions, GetTemplateResponses } from '../types/GetTemplate'
import { client } from '../.kubb/client'

/**
 * @summary Buscar modelo de documento
 * {@link /templates/:id}
 */
export function getTemplate<ThrowOnError extends boolean = true>(options: Options<GetTemplateOptions, ThrowOnError>): Promise<RequestResult<GetTemplateResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/templates/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<GetTemplateResponses, ThrowOnError>>
}