/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListEventsOptions, ListEventsResponses } from '../types/ListEvents'
import { client } from '../.kubb/client'

/**
 * @summary Listar eventos visíveis para o usuário logado
 * {@link /events}
 */
export function listEvents<ThrowOnError extends boolean = true>(options: Options<ListEventsOptions, ThrowOnError>): Promise<RequestResult<ListEventsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/events', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListEventsResponses, ThrowOnError>>
}