/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListClientsOptions, ListClientsResponses } from '../types/ListClients'
import { client } from '../.kubb/client'

/**
 * @summary Listar clientes
 * {@link /clients}
 */
export function listClients<ThrowOnError extends boolean = true>(options: Options<ListClientsOptions, ThrowOnError> = {}): Promise<RequestResult<ListClientsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/clients', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListClientsResponses, ThrowOnError>>
}