/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListDocumentsOptions, ListDocumentsResponses } from '../types/ListDocuments'
import { client } from '../.kubb/client'

/**
 * @summary Listar documentos do cliente
 * {@link /clients/:clientId/documents}
 */
export function listDocuments<ThrowOnError extends boolean = true>(options: Options<ListDocumentsOptions, ThrowOnError>): Promise<RequestResult<ListDocumentsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/clients/{clientId}/documents', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListDocumentsResponses, ThrowOnError>>
}