/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListIntakesOptions, ListIntakesResponses } from '../types/ListIntakes'
import { client } from '../.kubb/client'

/**
 * @summary Listar atendimentos do cliente
 * {@link /clients/:clientId/intakes}
 */
export function listIntakes<ThrowOnError extends boolean = true>(options: Options<ListIntakesOptions, ThrowOnError>): Promise<RequestResult<ListIntakesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/clients/{clientId}/intakes', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListIntakesResponses, ThrowOnError>>
}