/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListProcessMovementsOptions, ListProcessMovementsResponses } from '../types/ListProcessMovements'
import { client } from '../.kubb/client'

/**
 * @summary Listar movimentações do processo
 * {@link /processes/:processId/movements}
 */
export function listProcessMovements<ThrowOnError extends boolean = true>(options: Options<ListProcessMovementsOptions, ThrowOnError>): Promise<RequestResult<ListProcessMovementsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/processes/{processId}/movements', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListProcessMovementsResponses, ThrowOnError>>
}