/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListUsersOptions, ListUsersResponses } from '../types/ListUsers'
import { client } from '../.kubb/client'

/**
 * @summary Listar usuários
 * {@link /users}
 */
export function listUsers<ThrowOnError extends boolean = true>(options: Options<ListUsersOptions, ThrowOnError> = {}): Promise<RequestResult<ListUsersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/users', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListUsersResponses, ThrowOnError>>
}