/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTemplatesOptions, ListTemplatesResponses } from '../types/ListTemplates'
import { client } from '../.kubb/client'

/**
 * @summary Listar modelos de documento
 * {@link /templates}
 */
export function listTemplates<ThrowOnError extends boolean = true>(options: Options<ListTemplatesOptions, ThrowOnError> = {}): Promise<RequestResult<ListTemplatesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/templates', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListTemplatesResponses, ThrowOnError>>
}