/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListProcessesOptions, ListProcessesResponses } from '../types/ListProcesses'
import { client } from '../.kubb/client'

/**
 * @summary Listar processos
 * {@link /processes}
 */
export function listProcesses<ThrowOnError extends boolean = true>(options: Options<ListProcessesOptions, ThrowOnError> = {}): Promise<RequestResult<ListProcessesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/processes', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListProcessesResponses, ThrowOnError>>
}