/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListCompaniesOptions, ListCompaniesResponses } from '../types/ListCompanies'
import { client } from '../.kubb/client'

/**
 * @summary Listar empresas representadas pelo cliente
 * {@link /clients/:clientId/companies}
 */
export function listCompanies<ThrowOnError extends boolean = true>(options: Options<ListCompaniesOptions, ThrowOnError>): Promise<RequestResult<ListCompaniesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/clients/{clientId}/companies', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListCompaniesResponses, ThrowOnError>>
}