/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTasksOptions, ListTasksResponses } from '../types/ListTasks'
import { client } from '../.kubb/client'

/**
 * @summary Listar tarefas do usuário logado
 * {@link /tasks}
 */
export function listTasks<ThrowOnError extends boolean = true>(options: Options<ListTasksOptions, ThrowOnError> = {}): Promise<RequestResult<ListTasksResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/tasks', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<ListTasksResponses, ThrowOnError>>
}