/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { MoveTaskOptions, MoveTaskResponses } from '../types/MoveTask'
import { client } from '../.kubb/client'

/**
 * @summary Mover tarefa entre colunas e reordenar
 * {@link /tasks/:id/move}
 */
export function moveTask<ThrowOnError extends boolean = true>(options: Options<MoveTaskOptions, ThrowOnError>): Promise<RequestResult<MoveTaskResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/tasks/{id}/move', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<MoveTaskResponses, ThrowOnError>>
}