/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SendIntakeEmailOptions, SendIntakeEmailResponses } from '../types/SendIntakeEmail'
import { client } from '../.kubb/client'

/**
 * @summary Enviar a ficha do atendimento por e-mail ao cliente
 * {@link /intakes/:id/send}
 */
export function sendIntakeEmail<ThrowOnError extends boolean = true>(options: Options<SendIntakeEmailOptions, ThrowOnError>): Promise<RequestResult<SendIntakeEmailResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/intakes/{id}/send', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<SendIntakeEmailResponses, ThrowOnError>>
}