/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SignOutOptions, SignOutResponses } from '../types/SignOut'
import { client } from '../.kubb/client'

/**
 * @summary Sair do sistema
 * {@link /auth/sign-out}
 */
export function signOut<ThrowOnError extends boolean = true>(options: Options<SignOutOptions, ThrowOnError> = {}): Promise<RequestResult<SignOutResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/auth/sign-out', ...config }) as Promise<RequestResult<SignOutResponses, ThrowOnError>>
}