/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SignInOptions, SignInResponses } from '../types/SignIn'
import { client } from '../.kubb/client'

/**
 * @summary Entrar no sistema
 * {@link /auth/sign-in}
 */
export function signIn<ThrowOnError extends boolean = true>(options: Options<SignInOptions, ThrowOnError>): Promise<RequestResult<SignInResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/auth/sign-in', ...config }) as Promise<RequestResult<SignInResponses, ThrowOnError>>
}