/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateTaskOptions, UpdateTaskResponses } from '../types/UpdateTask'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar tarefa
 * {@link /tasks/:id}
 */
export function updateTask<ThrowOnError extends boolean = true>(options: Options<UpdateTaskOptions, ThrowOnError>): Promise<RequestResult<UpdateTaskResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/tasks/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateTaskResponses, ThrowOnError>>
}