/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateIntakeOptions, UpdateIntakeResponses } from '../types/UpdateIntake'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar atendimento
 * {@link /intakes/:id}
 */
export function updateIntake<ThrowOnError extends boolean = true>(options: Options<UpdateIntakeOptions, ThrowOnError>): Promise<RequestResult<UpdateIntakeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/intakes/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateIntakeResponses, ThrowOnError>>
}