/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateProcessOptions, UpdateProcessResponses } from '../types/UpdateProcess'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar processo
 * {@link /processes/:id}
 */
export function updateProcess<ThrowOnError extends boolean = true>(options: Options<UpdateProcessOptions, ThrowOnError>): Promise<RequestResult<UpdateProcessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/processes/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateProcessResponses, ThrowOnError>>
}