/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateClientOptions, UpdateClientResponses } from '../types/UpdateClient'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar cliente
 * {@link /clients/:id}
 */
export function updateClient<ThrowOnError extends boolean = true>(options: Options<UpdateClientOptions, ThrowOnError>): Promise<RequestResult<UpdateClientResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/clients/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateClientResponses, ThrowOnError>>
}