/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateCompanyOptions, UpdateCompanyResponses } from '../types/UpdateCompany'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar empresa
 * {@link /companies/:id}
 */
export function updateCompany<ThrowOnError extends boolean = true>(options: Options<UpdateCompanyOptions, ThrowOnError>): Promise<RequestResult<UpdateCompanyResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/companies/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateCompanyResponses, ThrowOnError>>
}