/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateEventOptions, UpdateEventResponses } from '../types/UpdateEvent'
import { client } from '../.kubb/client'

/**
 * @summary Atualizar evento
 * {@link /events/:id}
 */
export function updateEvent<ThrowOnError extends boolean = true>(options: Options<UpdateEventOptions, ThrowOnError>): Promise<RequestResult<UpdateEventResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/events/{id}', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UpdateEventResponses, ThrowOnError>>
}