/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UploadDocumentOptions, UploadDocumentResponses } from '../types/UploadDocument'
import { client } from '../.kubb/client'

/**
 * @summary Enviar documento
 * {@link /clients/:clientId/documents}
 */
export function uploadDocument<ThrowOnError extends boolean = true>(options: Options<UploadDocumentOptions, ThrowOnError>): Promise<RequestResult<UploadDocumentResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/clients/{clientId}/documents', security: [{ type: 'apiKey', name: 'token', in: 'cookie' }], ...config }) as Promise<RequestResult<UploadDocumentResponses, ThrowOnError>>
}