/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const activateAccountStatus200RoleEnum = {
    ADMIN: "ADMIN",
    MEMBER: "MEMBER"
} as const;

export type ActivateAccountStatus200RoleEnumKey = (typeof activateAccountStatus200RoleEnum)[keyof typeof activateAccountStatus200RoleEnum];

export type ActivateAccountStatus200 = {
    id: string;
    name: string;
    /**
     * @description
     * Format: `email`
     * @type string
    */
    email: string;
    role: ActivateAccountStatus200RoleEnumKey;
    isActive: boolean;
};

export type ActivateAccountBody = {
    /**
     * @minLength 1
     * @type string
    */
    token: string;
};

export type ActivateAccountOptions = {
    body: ActivateAccountBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type ActivateAccountResponses = {
    "200": ActivateAccountStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ActivateAccountResponse = ActivateAccountStatus200;