/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateClientStatus201 = {
    id: string;
    fullName: string;
    cpf: string;
};

export type CreateClientBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    fullName: string;
    /**
     * @minLength 11
     * @maxLength 14
     * @type string
    */
    cpf: string;
    /**
     * @maxLength 20
     * @type string | undefined
    */
    rg?: string;
    /**
     * @description
     * Format: `date`
     * @type string | undefined
    */
    birthDate?: string;
    /**
     * @maxLength 60
     * @type string | undefined
    */
    maritalStatus?: string;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    profession?: string;
    /**
     * @maxLength 30
     * @type string | undefined
    */
    phone?: string;
    /**
     * @description
     * Format: `email`
     * @type string | undefined
    */
    email?: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    address?: string;
    isActive?: boolean;
};

export type CreateClientOptions = {
    body: CreateClientBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateClientResponses = {
    "201": CreateClientStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateClientResponse = CreateClientStatus201;