/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateCompanyPath = {
    clientId: string;
};

export type CreateCompanyStatus201 = {
    id: string;
};

export type CreateCompanyBody = {
    /**
     * @minLength 14
     * @maxLength 18
     * @type string
    */
    cnpj: string;
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    razaoSocial: string;
    /**
     * @maxLength 180
     * @type string | undefined
    */
    nomeFantasia?: string;
    /**
     * @maxLength 30
     * @type string | undefined
    */
    phone?: string;
    /**
     * @description
     * Format: `email`
     * @type string | undefined
    */
    email?: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    address?: string;
    isActive?: boolean;
};

export type CreateCompanyOptions = {
    body: CreateCompanyBody;
    path: CreateCompanyPath;
    query?: never;
    headers?: never;
};

export type CreateCompanyResponses = {
    "201": CreateCompanyStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateCompanyResponse = CreateCompanyStatus201;