/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateIntakePreviewLinkPath = {
    id: string;
};

export type CreateIntakePreviewLinkStatus201 = {
    token: string;
    url: string;
};

export type CreateIntakePreviewLinkOptions = {
    body?: never;
    path: CreateIntakePreviewLinkPath;
    query?: never;
    headers?: never;
};

export type CreateIntakePreviewLinkResponses = {
    "201": CreateIntakePreviewLinkStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateIntakePreviewLinkResponse = CreateIntakePreviewLinkStatus201;