/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateProcessMovementPath = {
    processId: string;
};

export type CreateProcessMovementStatus201 = {
    id: string;
};

export type CreateProcessMovementBody = {
    /**
     * @minLength 1
     * @maxLength 2000
     * @type string
    */
    description: string;
    /**
     * @description
     * Format: `date`
     * @type string
    */
    occurredAt: string;
};

export type CreateProcessMovementOptions = {
    body: CreateProcessMovementBody;
    path: CreateProcessMovementPath;
    query?: never;
    headers?: never;
};

export type CreateProcessMovementResponses = {
    "201": CreateProcessMovementStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateProcessMovementResponse = CreateProcessMovementStatus201;