/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateUserStatus201 = {
    id: string;
};

export const createUserRequestRoleEnum = {
    ADMIN: "ADMIN",
    MEMBER: "MEMBER"
} as const;

export type CreateUserRequestRoleEnumKey = (typeof createUserRequestRoleEnum)[keyof typeof createUserRequestRoleEnum];

export type CreateUserBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    name: string;
    /**
     * @description
     * Format: `email`
     * @type string
    */
    email: string;
    role: CreateUserRequestRoleEnumKey;
};

export type CreateUserOptions = {
    body: CreateUserBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateUserResponses = {
    "201": CreateUserStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateUserResponse = CreateUserStatus201;