/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateProcessStatus201 = {
    id: string;
};

export type CreateProcessBody = {
    /**
     * @maxLength 30
     * @type string | undefined
    */
    caseNumber?: string;
    clientId: string;
    /**
     * @minLength 1
     * @type string
    */
    plaintiff: string;
    /**
     * @minLength 1
     * @type string
    */
    defendant: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    notes?: string;
};

export type CreateProcessOptions = {
    body: CreateProcessBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateProcessResponses = {
    "201": CreateProcessStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateProcessResponse = CreateProcessStatus201;