/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateEventStatus201 = {
    id: string;
};

export type CreateEventBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    title: string;
    /**
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startAt: string;
    isGlobal?: boolean;
    /**
     * @minLength 0
     * @maxLength 10080
     * @type integer | undefined
    */
    reminderMinutesBefore?: number;
};

export type CreateEventOptions = {
    body: CreateEventBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateEventResponses = {
    "201": CreateEventStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateEventResponse = CreateEventStatus201;