/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateTaskStatus201 = {
    id: string;
};

export const createTaskRequestStatusEnum = {
    TODO: "TODO",
    IN_PROGRESS: "IN_PROGRESS",
    DONE: "DONE"
} as const;

export type CreateTaskRequestStatusEnumKey = (typeof createTaskRequestStatusEnum)[keyof typeof createTaskRequestStatusEnum];

export type CreateTaskBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    title: string;
    /**
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string;
    /**
     * @description
     * Format: `date`
     * @type string | undefined
    */
    dueDate?: string;
    status?: CreateTaskRequestStatusEnumKey;
};

export type CreateTaskOptions = {
    body: CreateTaskBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateTaskResponses = {
    "201": CreateTaskStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateTaskResponse = CreateTaskStatus201;