/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateIntakePath = {
    clientId: string;
};

export type CreateIntakeStatus201 = {
    id: string;
};

export const createIntakeRequestPracticeAreasEnum = {
    PREVIDENCIARIO: "PREVIDENCIARIO",
    TRABALHISTA: "TRABALHISTA",
    CIVEL: "CIVEL",
    FAMILIA: "FAMILIA",
    CONSUMIDOR: "CONSUMIDOR",
    EMPRESARIAL: "EMPRESARIAL",
    CONTRATOS: "CONTRATOS",
    OUTRO: "OUTRO"
} as const;

export type CreateIntakeRequestPracticeAreasEnumKey = (typeof createIntakeRequestPracticeAreasEnum)[keyof typeof createIntakeRequestPracticeAreasEnum];

export const createIntakeRequestNextStepsEnum = {
    SOLICITAR_DOCUMENTOS: "SOLICITAR_DOCUMENTOS",
    ELABORAR_PARECER: "ELABORAR_PARECER",
    AGENDAR_RETORNO: "AGENDAR_RETORNO",
    ELABORAR_CONTRATO: "ELABORAR_CONTRATO",
    PROTOCOLAR_ACAO: "PROTOCOLAR_ACAO",
    TENTATIVA_ACORDO: "TENTATIVA_ACORDO",
    OUTRO: "OUTRO"
} as const;

export type CreateIntakeRequestNextStepsEnumKey = (typeof createIntakeRequestNextStepsEnum)[keyof typeof createIntakeRequestNextStepsEnum];

export const createIntakeRequestReferralSourceEnum = {
    INDICACAO: "INDICACAO",
    INSTAGRAM: "INSTAGRAM",
    FACEBOOK: "FACEBOOK",
    GOOGLE: "GOOGLE",
    SITE: "SITE",
    OUTRO: "OUTRO"
} as const;

export type CreateIntakeRequestReferralSourceEnumKey = (typeof createIntakeRequestReferralSourceEnum)[keyof typeof createIntakeRequestReferralSourceEnum];

export type CreateIntakeBody = {
    /**
     * @default
     * @type array | undefined
    */
    practiceAreas?: CreateIntakeRequestPracticeAreasEnumKey[];
    /**
     * @maxLength 120
     * @type string | undefined
    */
    practiceAreaOther?: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    clientReport?: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    lawyerAnalysis?: string;
    /**
     * @default
     * @type array | undefined
    */
    nextSteps?: CreateIntakeRequestNextStepsEnumKey[];
    /**
     * @maxLength 120
     * @type string | undefined
    */
    nextStepsOther?: string;
    /**
     * @minLength 0
     * @type number | undefined
    */
    feeAmount?: number;
    /**
     * @maxLength 60
     * @type string | undefined
    */
    paymentMethod?: string;
    referralSource?: CreateIntakeRequestReferralSourceEnumKey;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    referredByName?: string;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    referralSourceOther?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    lgpdConsent?: boolean;
};

export type CreateIntakeOptions = {
    body: CreateIntakeBody;
    path: CreateIntakePath;
    query?: never;
    headers?: never;
};

export type CreateIntakeResponses = {
    "201": CreateIntakeStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateIntakeResponse = CreateIntakeStatus201;