/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteProcessPath = {
    id: string;
};

export type DeleteProcessStatus200 = {
    id: string;
};

export type DeleteProcessOptions = {
    body?: never;
    path: DeleteProcessPath;
    query?: never;
    headers?: never;
};

export type DeleteProcessResponses = {
    "200": DeleteProcessStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteProcessResponse = DeleteProcessStatus200;