/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteIntakePath = {
    id: string;
};

export type DeleteIntakeStatus200 = {
    id: string;
};

export type DeleteIntakeOptions = {
    body?: never;
    path: DeleteIntakePath;
    query?: never;
    headers?: never;
};

export type DeleteIntakeResponses = {
    "200": DeleteIntakeStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteIntakeResponse = DeleteIntakeStatus200;