/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteEventPath = {
    id: string;
};

export type DeleteEventStatus200 = {
    id: string;
};

export type DeleteEventOptions = {
    body?: never;
    path: DeleteEventPath;
    query?: never;
    headers?: never;
};

export type DeleteEventResponses = {
    "200": DeleteEventStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteEventResponse = DeleteEventStatus200;