/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteTaskPath = {
    id: string;
};

export type DeleteTaskStatus200 = {
    id: string;
};

export type DeleteTaskOptions = {
    body?: never;
    path: DeleteTaskPath;
    query?: never;
    headers?: never;
};

export type DeleteTaskResponses = {
    "200": DeleteTaskStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteTaskResponse = DeleteTaskStatus200;