/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteCompanyPath = {
    id: string;
};

export type DeleteCompanyStatus200 = {
    id: string;
};

export type DeleteCompanyOptions = {
    body?: never;
    path: DeleteCompanyPath;
    query?: never;
    headers?: never;
};

export type DeleteCompanyResponses = {
    "200": DeleteCompanyStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteCompanyResponse = DeleteCompanyStatus200;