/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteDocumentPath = {
    id: string;
};

export type DeleteDocumentStatus200 = {
    id: string;
};

export type DeleteDocumentOptions = {
    body?: never;
    path: DeleteDocumentPath;
    query?: never;
    headers?: never;
};

export type DeleteDocumentResponses = {
    "200": DeleteDocumentStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteDocumentResponse = DeleteDocumentStatus200;