/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DownloadDocumentPath = {
    id: string;
};

export type DownloadDocumentStatus200 = any;

export type DownloadDocumentOptions = {
    body?: never;
    path: DownloadDocumentPath;
    query?: never;
    headers?: never;
};

export type DownloadDocumentResponses = {
    "200": DownloadDocumentStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DownloadDocumentResponse = DownloadDocumentStatus200;