/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetClientPath = {
    id: string;
};

export const getClientStatus200PersonTypeEnum = {
    FISICA: "FISICA",
    JURIDICA: "JURIDICA"
} as const;

export type GetClientStatus200PersonTypeEnumKey = (typeof getClientStatus200PersonTypeEnum)[keyof typeof getClientStatus200PersonTypeEnum];

export type GetClientStatus200 = {
    id: string;
    personType: GetClientStatus200PersonTypeEnumKey;
    fullName: string;
    cpf: string | null;
    rg: string | null;
    /**
     * @description
     * Format: `date`
     * @type string
    */
    birthDate: string | null;
    maritalStatus: string | null;
    profession: string | null;
    cnpj: string | null;
    razaoSocial: string | null;
    nomeFantasia: string | null;
    phone: string | null;
    email: string | null;
    address: string | null;
    isActive: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: string;
};

export type GetClientOptions = {
    body?: never;
    path: GetClientPath;
    query?: never;
    headers?: never;
};

export type GetClientResponses = {
    "200": GetClientStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetClientResponse = GetClientStatus200;