/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetCompanyPath = {
    id: string;
};

export type GetCompanyStatus200 = {
    id: string;
    cnpj: string;
    razaoSocial: string;
    nomeFantasia: string | null;
    phone: string | null;
    email: string | null;
    address: string | null;
    isActive: boolean;
    legalRepresentativeId: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: string;
};

export type GetCompanyOptions = {
    body?: never;
    path: GetCompanyPath;
    query?: never;
    headers?: never;
};

export type GetCompanyResponses = {
    "200": GetCompanyStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetCompanyResponse = GetCompanyStatus200;