/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetHealthStatus200 = any;

export type GetHealthOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetHealthResponses = {
    "200": GetHealthStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetHealthResponse = GetHealthStatus200;