/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetOpenapiJsonStatus200 = any;

export type GetOpenapiJsonOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetOpenapiJsonResponses = {
    "200": GetOpenapiJsonStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetOpenapiJsonResponse = GetOpenapiJsonStatus200;