/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetProcessPath = {
    id: string;
};

export type GetProcessStatus200 = {
    id: string;
    caseNumber: string | null;
    clientId: string;
    plaintiff: string;
    defendant: string;
    notes: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    updatedAt: string;
    client: {
        id: string;
        fullName: string;
    };
    user: {
        id: string;
        name: string;
    };
};

export type GetProcessOptions = {
    body?: never;
    path: GetProcessPath;
    query?: never;
    headers?: never;
};

export type GetProcessResponses = {
    "200": GetProcessStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetProcessResponse = GetProcessStatus200;