/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetPublicPreviewQuery = {
    /**
     * @minLength 1
     * @type string
    */
    token: string;
};

export const getPublicPreviewStatus200IntakePracticeAreasEnum = {
    PREVIDENCIARIO: "PREVIDENCIARIO",
    TRABALHISTA: "TRABALHISTA",
    CIVEL: "CIVEL",
    FAMILIA: "FAMILIA",
    CONSUMIDOR: "CONSUMIDOR",
    EMPRESARIAL: "EMPRESARIAL",
    CONTRATOS: "CONTRATOS",
    OUTRO: "OUTRO"
} as const;

export type GetPublicPreviewStatus200IntakePracticeAreasEnumKey = (typeof getPublicPreviewStatus200IntakePracticeAreasEnum)[keyof typeof getPublicPreviewStatus200IntakePracticeAreasEnum];

export const getPublicPreviewStatus200IntakeNextStepsEnum = {
    SOLICITAR_DOCUMENTOS: "SOLICITAR_DOCUMENTOS",
    ELABORAR_PARECER: "ELABORAR_PARECER",
    AGENDAR_RETORNO: "AGENDAR_RETORNO",
    ELABORAR_CONTRATO: "ELABORAR_CONTRATO",
    PROTOCOLAR_ACAO: "PROTOCOLAR_ACAO",
    TENTATIVA_ACORDO: "TENTATIVA_ACORDO",
    OUTRO: "OUTRO"
} as const;

export type GetPublicPreviewStatus200IntakeNextStepsEnumKey = (typeof getPublicPreviewStatus200IntakeNextStepsEnum)[keyof typeof getPublicPreviewStatus200IntakeNextStepsEnum];

export const getPublicPreviewStatus200IntakeReferralSourceEnum = {
    INDICACAO: "INDICACAO",
    INSTAGRAM: "INSTAGRAM",
    FACEBOOK: "FACEBOOK",
    GOOGLE: "GOOGLE",
    SITE: "SITE",
    OUTRO: "OUTRO"
} as const;

export type GetPublicPreviewStatus200IntakeReferralSourceEnumKey = (typeof getPublicPreviewStatus200IntakeReferralSourceEnum)[keyof typeof getPublicPreviewStatus200IntakeReferralSourceEnum];

export type GetPublicPreviewStatus200 = {
    type: "intake";
    intake: {
        id: string;
        clientId: string;
        practiceAreas: GetPublicPreviewStatus200IntakePracticeAreasEnumKey[];
        practiceAreaOther: string | null;
        clientReport: string | null;
        lawyerAnalysis: string | null;
        nextSteps: GetPublicPreviewStatus200IntakeNextStepsEnumKey[];
        nextStepsOther: string | null;
        feeAmount: number | null;
        paymentMethod: string | null;
        referralSource: GetPublicPreviewStatus200IntakeReferralSourceEnumKey | null;
        referredByName: string | null;
        referralSourceOther: string | null;
        lgpdConsent: boolean;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        updatedAt: string;
        user: {
            id: string;
            name: string;
        };
    };
    client: {
        id: string;
        fullName: string;
        cpf: string;
        rg: string | null;
        /**
         * @description
         * Format: `date`
         * @type string
        */
        birthDate: string | null;
        maritalStatus: string | null;
        profession: string | null;
        phone: string | null;
        email: string | null;
        address: string | null;
        isActive: boolean;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
    };
};

export type GetPublicPreviewOptions = {
    body?: never;
    path?: never;
    query: GetPublicPreviewQuery;
    headers?: never;
};

export type GetPublicPreviewResponses = {
    "200": GetPublicPreviewStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetPublicPreviewResponse = GetPublicPreviewStatus200;