/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const listUsersStatus200DataRoleEnum = {
    ADMIN: "ADMIN",
    MEMBER: "MEMBER"
} as const;

export type ListUsersStatus200DataRoleEnumKey = (typeof listUsersStatus200DataRoleEnum)[keyof typeof listUsersStatus200DataRoleEnum];

export type ListUsersStatus200 = {
    data: {
        id: string;
        name: string;
        email: string;
        role: ListUsersStatus200DataRoleEnumKey;
        isActive: boolean;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
    }[];
};

export type ListUsersOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type ListUsersResponses = {
    "200": ListUsersStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListUsersResponse = ListUsersStatus200;