/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const listClientsIsActive = {
    true: "true",
    false: "false"
} as const;

export type ListClientsIsActiveKey = (typeof listClientsIsActive)[keyof typeof listClientsIsActive];

export type ListClientsQuery = {
    /**
     * @minLength 1
     * @maxLength 9007199254740991
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type integer | undefined
    */
    pageSize?: number;
    /**
     * @minLength 1
     * @type string | undefined
    */
    search?: string;
    isActive?: ListClientsIsActiveKey;
};

export type ListClientsStatus200 = {
    data: {
        id: string;
        fullName: string;
        cpf: string;
        rg: string | null;
        /**
         * @description
         * Format: `date`
         * @type string
        */
        birthDate: string | null;
        maritalStatus: string | null;
        profession: string | null;
        phone: string | null;
        email: string | null;
        address: string | null;
        isActive: boolean;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
    }[];
    pagination: {
        page: number;
        pageSize: number;
        total: number;
        pageCount: number;
    };
};

export type ListClientsOptions = {
    body?: never;
    path?: never;
    query?: ListClientsQuery;
    headers?: never;
};

export type ListClientsResponses = {
    "200": ListClientsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListClientsResponse = ListClientsStatus200;