/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListDocumentsPath = {
    clientId: string;
};

export type ListDocumentsStatus200 = {
    data: {
        id: string;
        clientId: string;
        originalName: string;
        mimeType: string;
        size: number;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
    }[];
};

export type ListDocumentsOptions = {
    body?: never;
    path: ListDocumentsPath;
    query?: never;
    headers?: never;
};

export type ListDocumentsResponses = {
    "200": ListDocumentsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListDocumentsResponse = ListDocumentsStatus200;