/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListIntakesPath = {
    clientId: string;
};

export type ListIntakesQuery = {
    /**
     * @minLength 1
     * @maxLength 9007199254740991
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type integer | undefined
    */
    pageSize?: number;
};

export const listIntakesStatus200DataPracticeAreasEnum = {
    PREVIDENCIARIO: "PREVIDENCIARIO",
    TRABALHISTA: "TRABALHISTA",
    CIVEL: "CIVEL",
    FAMILIA: "FAMILIA",
    CONSUMIDOR: "CONSUMIDOR",
    EMPRESARIAL: "EMPRESARIAL",
    CONTRATOS: "CONTRATOS",
    OUTRO: "OUTRO"
} as const;

export type ListIntakesStatus200DataPracticeAreasEnumKey = (typeof listIntakesStatus200DataPracticeAreasEnum)[keyof typeof listIntakesStatus200DataPracticeAreasEnum];

export const listIntakesStatus200DataNextStepsEnum = {
    SOLICITAR_DOCUMENTOS: "SOLICITAR_DOCUMENTOS",
    ELABORAR_PARECER: "ELABORAR_PARECER",
    AGENDAR_RETORNO: "AGENDAR_RETORNO",
    ELABORAR_CONTRATO: "ELABORAR_CONTRATO",
    PROTOCOLAR_ACAO: "PROTOCOLAR_ACAO",
    TENTATIVA_ACORDO: "TENTATIVA_ACORDO",
    OUTRO: "OUTRO"
} as const;

export type ListIntakesStatus200DataNextStepsEnumKey = (typeof listIntakesStatus200DataNextStepsEnum)[keyof typeof listIntakesStatus200DataNextStepsEnum];

export const listIntakesStatus200DataReferralSourceEnum = {
    INDICACAO: "INDICACAO",
    INSTAGRAM: "INSTAGRAM",
    FACEBOOK: "FACEBOOK",
    GOOGLE: "GOOGLE",
    SITE: "SITE",
    OUTRO: "OUTRO"
} as const;

export type ListIntakesStatus200DataReferralSourceEnumKey = (typeof listIntakesStatus200DataReferralSourceEnum)[keyof typeof listIntakesStatus200DataReferralSourceEnum];

export type ListIntakesStatus200 = {
    data: {
        id: string;
        clientId: string;
        practiceAreas: ListIntakesStatus200DataPracticeAreasEnumKey[];
        practiceAreaOther: string | null;
        clientReport: string | null;
        lawyerAnalysis: string | null;
        nextSteps: ListIntakesStatus200DataNextStepsEnumKey[];
        nextStepsOther: string | null;
        feeAmount: number | null;
        paymentMethod: string | null;
        referralSource: ListIntakesStatus200DataReferralSourceEnumKey | null;
        referredByName: string | null;
        referralSourceOther: string | null;
        lgpdConsent: boolean;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        updatedAt: string;
        user: {
            id: string;
            name: string;
        };
    }[];
    pagination: {
        page: number;
        pageSize: number;
        total: number;
        pageCount: number;
    };
};

export type ListIntakesOptions = {
    body?: never;
    path: ListIntakesPath;
    query?: ListIntakesQuery;
    headers?: never;
};

export type ListIntakesResponses = {
    "200": ListIntakesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListIntakesResponse = ListIntakesStatus200;