/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListTemplatesStatus200 = {
    data: {
        id: string;
        name: string;
        description: string;
    }[];
};

export type ListTemplatesOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type ListTemplatesResponses = {
    "200": ListTemplatesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListTemplatesResponse = ListTemplatesStatus200;