/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListProcessMovementsPath = {
    processId: string;
};

export type ListProcessMovementsStatus200 = {
    data: {
        id: string;
        processId: string;
        description: string;
        /**
         * @description
         * Format: `date`
         * @type string
        */
        occurredAt: string;
        /**
         * @description
         * Format: `date-time`
         * @type string
        */
        createdAt: string;
    }[];
};

export type ListProcessMovementsOptions = {
    body?: never;
    path: ListProcessMovementsPath;
    query?: never;
    headers?: never;
};

export type ListProcessMovementsResponses = {
    "200": ListProcessMovementsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListProcessMovementsResponse = ListProcessMovementsStatus200;