/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type MoveTaskPath = {
    id: string;
};

export type MoveTaskStatus200 = {
    id: string;
};

export const moveTaskRequestStatusEnum = {
    TODO: "TODO",
    IN_PROGRESS: "IN_PROGRESS",
    DONE: "DONE"
} as const;

export type MoveTaskRequestStatusEnumKey = (typeof moveTaskRequestStatusEnum)[keyof typeof moveTaskRequestStatusEnum];

export type MoveTaskBody = {
    status: MoveTaskRequestStatusEnumKey;
    orderedIds: string[];
};

export type MoveTaskOptions = {
    body: MoveTaskBody;
    path: MoveTaskPath;
    query?: never;
    headers?: never;
};

export type MoveTaskResponses = {
    "200": MoveTaskStatus200;
};

/**
 * @description Union of all possible responses
*/
export type MoveTaskResponse = MoveTaskStatus200;