/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type SendIntakeEmailPath = {
    id: string;
};

export type SendIntakeEmailStatus200 = {
    sentTo: string;
};

export type SendIntakeEmailOptions = {
    body?: never;
    path: SendIntakeEmailPath;
    query?: never;
    headers?: never;
};

export type SendIntakeEmailResponses = {
    "200": SendIntakeEmailStatus200;
};

/**
 * @description Union of all possible responses
*/
export type SendIntakeEmailResponse = SendIntakeEmailStatus200;