/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const signInStatus200RoleEnum = {
    ADMIN: "ADMIN",
    MEMBER: "MEMBER"
} as const;

export type SignInStatus200RoleEnumKey = (typeof signInStatus200RoleEnum)[keyof typeof signInStatus200RoleEnum];

export type SignInStatus200 = {
    id: string;
    name: string;
    /**
     * @description
     * Format: `email`
     * @type string
    */
    email: string;
    role: SignInStatus200RoleEnumKey;
    isActive: boolean;
};

export type SignInBody = {
    /**
     * @description
     * Format: `email`
     * @type string
    */
    email: string;
    /**
     * @minLength 1
     * @type string
    */
    password: string;
};

export type SignInOptions = {
    body: SignInBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type SignInResponses = {
    "200": SignInStatus200;
};

/**
 * @description Union of all possible responses
*/
export type SignInResponse = SignInStatus200;