/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateEventPath = {
    id: string;
};

export type UpdateEventStatus200 = {
    id: string;
};

export type UpdateEventBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    title: string;
    /**
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startAt: string;
    isGlobal?: boolean;
    /**
     * @minLength 0
     * @maxLength 10080
     * @type integer | undefined
    */
    reminderMinutesBefore?: number;
};

export type UpdateEventOptions = {
    body: UpdateEventBody;
    path: UpdateEventPath;
    query?: never;
    headers?: never;
};

export type UpdateEventResponses = {
    "200": UpdateEventStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateEventResponse = UpdateEventStatus200;