/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateTaskPath = {
    id: string;
};

export type UpdateTaskStatus200 = {
    id: string;
};

export type UpdateTaskBody = {
    /**
     * @minLength 1
     * @maxLength 180
     * @type string | undefined
    */
    title?: string;
    /**
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string;
    /**
     * @description
     * Format: `date`
     * @type string | undefined
    */
    dueDate?: string;
};

export type UpdateTaskOptions = {
    body: UpdateTaskBody;
    path: UpdateTaskPath;
    query?: never;
    headers?: never;
};

export type UpdateTaskResponses = {
    "200": UpdateTaskStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateTaskResponse = UpdateTaskStatus200;