/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateClientPath = {
    id: string;
};

export type UpdateClientStatus200 = {
    id: string;
    fullName: string;
    cpf: string | null;
    cnpj: string | null;
};

export type UpdateClientBody = ({
    /**
     * @maxLength 30
     * @type string | undefined
    */
    phone?: string;
    /**
     * @description
     * Format: `email`
     * @type string | undefined
    */
    email?: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    address?: string;
    isActive?: boolean;
    personType: "FISICA";
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    fullName: string;
    /**
     * @minLength 11
     * @maxLength 14
     * @type string
    */
    cpf: string;
    /**
     * @maxLength 20
     * @type string | undefined
    */
    rg?: string;
    /**
     * @description
     * Format: `date`
     * @type string | undefined
    */
    birthDate?: string;
    /**
     * @maxLength 60
     * @type string | undefined
    */
    maritalStatus?: string;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    profession?: string;
} | {
    /**
     * @maxLength 30
     * @type string | undefined
    */
    phone?: string;
    /**
     * @description
     * Format: `email`
     * @type string | undefined
    */
    email?: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    address?: string;
    isActive?: boolean;
    personType: "JURIDICA";
    /**
     * @minLength 14
     * @maxLength 18
     * @type string
    */
    cnpj: string;
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    razaoSocial: string;
    /**
     * @maxLength 180
     * @type string | undefined
    */
    nomeFantasia?: string;
});

export type UpdateClientOptions = {
    body: UpdateClientBody;
    path: UpdateClientPath;
    query?: never;
    headers?: never;
};

export type UpdateClientResponses = {
    "200": UpdateClientStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateClientResponse = UpdateClientStatus200;