/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateCompanyPath = {
    id: string;
};

export type UpdateCompanyStatus200 = {
    id: string;
};

export type UpdateCompanyBody = {
    /**
     * @minLength 14
     * @maxLength 18
     * @type string
    */
    cnpj: string;
    /**
     * @minLength 1
     * @maxLength 180
     * @type string
    */
    razaoSocial: string;
    /**
     * @maxLength 180
     * @type string | undefined
    */
    nomeFantasia?: string;
    /**
     * @maxLength 30
     * @type string | undefined
    */
    phone?: string;
    /**
     * @description
     * Format: `email`
     * @type string | undefined
    */
    email?: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    address?: string;
    isActive?: boolean;
};

export type UpdateCompanyOptions = {
    body: UpdateCompanyBody;
    path: UpdateCompanyPath;
    query?: never;
    headers?: never;
};

export type UpdateCompanyResponses = {
    "200": UpdateCompanyStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateCompanyResponse = UpdateCompanyStatus200;