/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateProcessPath = {
    id: string;
};

export type UpdateProcessStatus200 = {
    id: string;
};

export type UpdateProcessBody = {
    /**
     * @maxLength 30
     * @type string | undefined
    */
    caseNumber?: string;
    clientId: string;
    /**
     * @minLength 1
     * @type string
    */
    plaintiff: string;
    /**
     * @minLength 1
     * @type string
    */
    defendant: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    notes?: string;
};

export type UpdateProcessOptions = {
    body: UpdateProcessBody;
    path: UpdateProcessPath;
    query?: never;
    headers?: never;
};

export type UpdateProcessResponses = {
    "200": UpdateProcessStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateProcessResponse = UpdateProcessStatus200;