/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateIntakePath = {
    id: string;
};

export type UpdateIntakeStatus200 = {
    id: string;
};

export const updateIntakeRequestPracticeAreasEnum = {
    PREVIDENCIARIO: "PREVIDENCIARIO",
    TRABALHISTA: "TRABALHISTA",
    CIVEL: "CIVEL",
    FAMILIA: "FAMILIA",
    CONSUMIDOR: "CONSUMIDOR",
    EMPRESARIAL: "EMPRESARIAL",
    CONTRATOS: "CONTRATOS",
    OUTRO: "OUTRO"
} as const;

export type UpdateIntakeRequestPracticeAreasEnumKey = (typeof updateIntakeRequestPracticeAreasEnum)[keyof typeof updateIntakeRequestPracticeAreasEnum];

export const updateIntakeRequestNextStepsEnum = {
    SOLICITAR_DOCUMENTOS: "SOLICITAR_DOCUMENTOS",
    ELABORAR_PARECER: "ELABORAR_PARECER",
    AGENDAR_RETORNO: "AGENDAR_RETORNO",
    ELABORAR_CONTRATO: "ELABORAR_CONTRATO",
    PROTOCOLAR_ACAO: "PROTOCOLAR_ACAO",
    TENTATIVA_ACORDO: "TENTATIVA_ACORDO",
    OUTRO: "OUTRO"
} as const;

export type UpdateIntakeRequestNextStepsEnumKey = (typeof updateIntakeRequestNextStepsEnum)[keyof typeof updateIntakeRequestNextStepsEnum];

export const updateIntakeRequestReferralSourceEnum = {
    INDICACAO: "INDICACAO",
    INSTAGRAM: "INSTAGRAM",
    FACEBOOK: "FACEBOOK",
    GOOGLE: "GOOGLE",
    SITE: "SITE",
    OUTRO: "OUTRO"
} as const;

export type UpdateIntakeRequestReferralSourceEnumKey = (typeof updateIntakeRequestReferralSourceEnum)[keyof typeof updateIntakeRequestReferralSourceEnum];

export type UpdateIntakeBody = {
    /**
     * @default
     * @type array | undefined
    */
    practiceAreas?: UpdateIntakeRequestPracticeAreasEnumKey[];
    /**
     * @maxLength 120
     * @type string | undefined
    */
    practiceAreaOther?: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    clientReport?: string;
    /**
     * @maxLength 5000
     * @type string | undefined
    */
    lawyerAnalysis?: string;
    /**
     * @default
     * @type array | undefined
    */
    nextSteps?: UpdateIntakeRequestNextStepsEnumKey[];
    /**
     * @maxLength 120
     * @type string | undefined
    */
    nextStepsOther?: string;
    /**
     * @minLength 0
     * @type number | undefined
    */
    feeAmount?: number;
    /**
     * @maxLength 60
     * @type string | undefined
    */
    paymentMethod?: string;
    referralSource?: UpdateIntakeRequestReferralSourceEnumKey;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    referredByName?: string;
    /**
     * @maxLength 120
     * @type string | undefined
    */
    referralSourceOther?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    lgpdConsent?: boolean;
};

export type UpdateIntakeOptions = {
    body: UpdateIntakeBody;
    path: UpdateIntakePath;
    query?: never;
    headers?: never;
};

export type UpdateIntakeResponses = {
    "200": UpdateIntakeStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateIntakeResponse = UpdateIntakeStatus200;