/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UploadDocumentPath = {
    clientId: string;
};

export type UploadDocumentStatus201 = {
    id: string;
    clientId: string;
    companyId: string | null;
    originalName: string;
    mimeType: string;
    size: number;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: string;
};

export type UploadDocumentOptions = {
    body?: never;
    path: UploadDocumentPath;
    query?: never;
    headers?: never;
};

export type UploadDocumentResponses = {
    "201": UploadDocumentStatus201;
};

/**
 * @description Union of all possible responses
*/
export type UploadDocumentResponse = UploadDocumentStatus201;