/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ActivateAccountOptions, ActivateAccountStatus200 } from '../types/ActivateAccount'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { activateAccount } from '../clients/activateAccount'

export const activateAccountMutationKey = () => [{ url: '/auth/activate' }] as const

export function activateAccountMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = activateAccountMutationKey()
  return mutationOptions<ActivateAccountStatus200, ResponseErrorConfig<Error>, ActivateAccountOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await activateAccount({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Ativar conta a partir do link enviado por e-mail
 * {@link /auth/activate}
 */
export function useActivateAccount<TContext>(options: {
  mutation?: UseMutationOptions<ActivateAccountStatus200, ResponseErrorConfig<Error>, ActivateAccountOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? activateAccountMutationKey()

  const baseOptions = activateAccountMutationOptions(config) as UseMutationOptions<ActivateAccountStatus200, ResponseErrorConfig<Error>, ActivateAccountOptions, TContext>

  return useMutation<ActivateAccountStatus200, ResponseErrorConfig<Error>, ActivateAccountOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ActivateAccountStatus200, ResponseErrorConfig<Error>, ActivateAccountOptions, TContext>
}