/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateProcessMovementOptions, CreateProcessMovementStatus201 } from '../types/CreateProcessMovement'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createProcessMovement } from '../clients/createProcessMovement'

export const createProcessMovementMutationKey = () => [{ url: '/processes/:processId/movements' }] as const

export function createProcessMovementMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createProcessMovementMutationKey()
  return mutationOptions<CreateProcessMovementStatus201, ResponseErrorConfig<Error>, CreateProcessMovementOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await createProcessMovement({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar movimentação do processo
 * {@link /processes/:processId/movements}
 */
export function useCreateProcessMovement<TContext>(options: {
  mutation?: UseMutationOptions<CreateProcessMovementStatus201, ResponseErrorConfig<Error>, CreateProcessMovementOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createProcessMovementMutationKey()

  const baseOptions = createProcessMovementMutationOptions(config) as UseMutationOptions<CreateProcessMovementStatus201, ResponseErrorConfig<Error>, CreateProcessMovementOptions, TContext>

  return useMutation<CreateProcessMovementStatus201, ResponseErrorConfig<Error>, CreateProcessMovementOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateProcessMovementStatus201, ResponseErrorConfig<Error>, CreateProcessMovementOptions, TContext>
}