/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateCompanyOptions, CreateCompanyStatus201 } from '../types/CreateCompany'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createCompany } from '../clients/createCompany'

export const createCompanyMutationKey = () => [{ url: '/clients/:clientId/companies' }] as const

export function createCompanyMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createCompanyMutationKey()
  return mutationOptions<CreateCompanyStatus201, ResponseErrorConfig<Error>, CreateCompanyOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await createCompany({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Cadastrar empresa representada pelo cliente
 * {@link /clients/:clientId/companies}
 */
export function useCreateCompany<TContext>(options: {
  mutation?: UseMutationOptions<CreateCompanyStatus201, ResponseErrorConfig<Error>, CreateCompanyOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createCompanyMutationKey()

  const baseOptions = createCompanyMutationOptions(config) as UseMutationOptions<CreateCompanyStatus201, ResponseErrorConfig<Error>, CreateCompanyOptions, TContext>

  return useMutation<CreateCompanyStatus201, ResponseErrorConfig<Error>, CreateCompanyOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateCompanyStatus201, ResponseErrorConfig<Error>, CreateCompanyOptions, TContext>
}