/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateClientOptions, CreateClientStatus201 } from '../types/CreateClient'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createClient } from '../clients/createClient'

export const createClientMutationKey = () => [{ url: '/clients' }] as const

export function createClientMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createClientMutationKey()
  return mutationOptions<CreateClientStatus201, ResponseErrorConfig<Error>, CreateClientOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createClient({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar cliente
 * {@link /clients}
 */
export function useCreateClient<TContext>(options: {
  mutation?: UseMutationOptions<CreateClientStatus201, ResponseErrorConfig<Error>, CreateClientOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createClientMutationKey()

  const baseOptions = createClientMutationOptions(config) as UseMutationOptions<CreateClientStatus201, ResponseErrorConfig<Error>, CreateClientOptions, TContext>

  return useMutation<CreateClientStatus201, ResponseErrorConfig<Error>, CreateClientOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateClientStatus201, ResponseErrorConfig<Error>, CreateClientOptions, TContext>
}