/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateIntakePreviewLinkOptions, CreateIntakePreviewLinkStatus201 } from '../types/CreateIntakePreviewLink'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createIntakePreviewLink } from '../clients/createIntakePreviewLink'

export const createIntakePreviewLinkMutationKey = () => [{ url: '/intakes/:id/preview-link' }] as const

export function createIntakePreviewLinkMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createIntakePreviewLinkMutationKey()
  return mutationOptions<CreateIntakePreviewLinkStatus201, ResponseErrorConfig<Error>, CreateIntakePreviewLinkOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await createIntakePreviewLink({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Gerar link público de visualização do atendimento
 * {@link /intakes/:id/preview-link}
 */
export function useCreateIntakePreviewLink<TContext>(options: {
  mutation?: UseMutationOptions<CreateIntakePreviewLinkStatus201, ResponseErrorConfig<Error>, CreateIntakePreviewLinkOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createIntakePreviewLinkMutationKey()

  const baseOptions = createIntakePreviewLinkMutationOptions(config) as UseMutationOptions<CreateIntakePreviewLinkStatus201, ResponseErrorConfig<Error>, CreateIntakePreviewLinkOptions, TContext>

  return useMutation<CreateIntakePreviewLinkStatus201, ResponseErrorConfig<Error>, CreateIntakePreviewLinkOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateIntakePreviewLinkStatus201, ResponseErrorConfig<Error>, CreateIntakePreviewLinkOptions, TContext>
}