/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateIntakeOptions, CreateIntakeStatus201 } from '../types/CreateIntake'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createIntake } from '../clients/createIntake'

export const createIntakeMutationKey = () => [{ url: '/clients/:clientId/intakes' }] as const

export function createIntakeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createIntakeMutationKey()
  return mutationOptions<CreateIntakeStatus201, ResponseErrorConfig<Error>, CreateIntakeOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await createIntake({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar atendimento
 * {@link /clients/:clientId/intakes}
 */
export function useCreateIntake<TContext>(options: {
  mutation?: UseMutationOptions<CreateIntakeStatus201, ResponseErrorConfig<Error>, CreateIntakeOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createIntakeMutationKey()

  const baseOptions = createIntakeMutationOptions(config) as UseMutationOptions<CreateIntakeStatus201, ResponseErrorConfig<Error>, CreateIntakeOptions, TContext>

  return useMutation<CreateIntakeStatus201, ResponseErrorConfig<Error>, CreateIntakeOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateIntakeStatus201, ResponseErrorConfig<Error>, CreateIntakeOptions, TContext>
}