/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateTaskOptions, CreateTaskStatus201 } from '../types/CreateTask'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createTask } from '../clients/createTask'

export const createTaskMutationKey = () => [{ url: '/tasks' }] as const

export function createTaskMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createTaskMutationKey()
  return mutationOptions<CreateTaskStatus201, ResponseErrorConfig<Error>, CreateTaskOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createTask({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar tarefa
 * {@link /tasks}
 */
export function useCreateTask<TContext>(options: {
  mutation?: UseMutationOptions<CreateTaskStatus201, ResponseErrorConfig<Error>, CreateTaskOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createTaskMutationKey()

  const baseOptions = createTaskMutationOptions(config) as UseMutationOptions<CreateTaskStatus201, ResponseErrorConfig<Error>, CreateTaskOptions, TContext>

  return useMutation<CreateTaskStatus201, ResponseErrorConfig<Error>, CreateTaskOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateTaskStatus201, ResponseErrorConfig<Error>, CreateTaskOptions, TContext>
}