/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateEventOptions, CreateEventStatus201 } from '../types/CreateEvent'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createEvent } from '../clients/createEvent'

export const createEventMutationKey = () => [{ url: '/events' }] as const

export function createEventMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createEventMutationKey()
  return mutationOptions<CreateEventStatus201, ResponseErrorConfig<Error>, CreateEventOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createEvent({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar evento
 * {@link /events}
 */
export function useCreateEvent<TContext>(options: {
  mutation?: UseMutationOptions<CreateEventStatus201, ResponseErrorConfig<Error>, CreateEventOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createEventMutationKey()

  const baseOptions = createEventMutationOptions(config) as UseMutationOptions<CreateEventStatus201, ResponseErrorConfig<Error>, CreateEventOptions, TContext>

  return useMutation<CreateEventStatus201, ResponseErrorConfig<Error>, CreateEventOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateEventStatus201, ResponseErrorConfig<Error>, CreateEventOptions, TContext>
}