/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateProcessOptions, CreateProcessStatus201 } from '../types/CreateProcess'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createProcess } from '../clients/createProcess'

export const createProcessMutationKey = () => [{ url: '/processes' }] as const

export function createProcessMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createProcessMutationKey()
  return mutationOptions<CreateProcessStatus201, ResponseErrorConfig<Error>, CreateProcessOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createProcess({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Criar processo
 * {@link /processes}
 */
export function useCreateProcess<TContext>(options: {
  mutation?: UseMutationOptions<CreateProcessStatus201, ResponseErrorConfig<Error>, CreateProcessOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createProcessMutationKey()

  const baseOptions = createProcessMutationOptions(config) as UseMutationOptions<CreateProcessStatus201, ResponseErrorConfig<Error>, CreateProcessOptions, TContext>

  return useMutation<CreateProcessStatus201, ResponseErrorConfig<Error>, CreateProcessOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateProcessStatus201, ResponseErrorConfig<Error>, CreateProcessOptions, TContext>
}