/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateUserOptions, CreateUserStatus201 } from '../types/CreateUser'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createUser } from '../clients/createUser'

export const createUserMutationKey = () => [{ url: '/users' }] as const

export function createUserMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createUserMutationKey()
  return mutationOptions<CreateUserStatus201, ResponseErrorConfig<Error>, CreateUserOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createUser({ ...config, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Cadastrar usuário
 * {@link /users}
 */
export function useCreateUser<TContext>(options: {
  mutation?: UseMutationOptions<CreateUserStatus201, ResponseErrorConfig<Error>, CreateUserOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createUserMutationKey()

  const baseOptions = createUserMutationOptions(config) as UseMutationOptions<CreateUserStatus201, ResponseErrorConfig<Error>, CreateUserOptions, TContext>

  return useMutation<CreateUserStatus201, ResponseErrorConfig<Error>, CreateUserOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateUserStatus201, ResponseErrorConfig<Error>, CreateUserOptions, TContext>
}