/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteCompanyOptions, DeleteCompanyStatus200 } from '../types/DeleteCompany'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteCompany } from '../clients/deleteCompany'

export const deleteCompanyMutationKey = () => [{ url: '/companies/:id' }] as const

export function deleteCompanyMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteCompanyMutationKey()
  return mutationOptions<DeleteCompanyStatus200, ResponseErrorConfig<Error>, DeleteCompanyOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteCompany({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir empresa
 * {@link /companies/:id}
 */
export function useDeleteCompany<TContext>(options: {
  mutation?: UseMutationOptions<DeleteCompanyStatus200, ResponseErrorConfig<Error>, DeleteCompanyOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteCompanyMutationKey()

  const baseOptions = deleteCompanyMutationOptions(config) as UseMutationOptions<DeleteCompanyStatus200, ResponseErrorConfig<Error>, DeleteCompanyOptions, TContext>

  return useMutation<DeleteCompanyStatus200, ResponseErrorConfig<Error>, DeleteCompanyOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteCompanyStatus200, ResponseErrorConfig<Error>, DeleteCompanyOptions, TContext>
}