/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteEventOptions, DeleteEventStatus200 } from '../types/DeleteEvent'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteEvent } from '../clients/deleteEvent'

export const deleteEventMutationKey = () => [{ url: '/events/:id' }] as const

export function deleteEventMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteEventMutationKey()
  return mutationOptions<DeleteEventStatus200, ResponseErrorConfig<Error>, DeleteEventOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteEvent({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir evento
 * {@link /events/:id}
 */
export function useDeleteEvent<TContext>(options: {
  mutation?: UseMutationOptions<DeleteEventStatus200, ResponseErrorConfig<Error>, DeleteEventOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteEventMutationKey()

  const baseOptions = deleteEventMutationOptions(config) as UseMutationOptions<DeleteEventStatus200, ResponseErrorConfig<Error>, DeleteEventOptions, TContext>

  return useMutation<DeleteEventStatus200, ResponseErrorConfig<Error>, DeleteEventOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteEventStatus200, ResponseErrorConfig<Error>, DeleteEventOptions, TContext>
}