/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteTaskOptions, DeleteTaskStatus200 } from '../types/DeleteTask'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteTask } from '../clients/deleteTask'

export const deleteTaskMutationKey = () => [{ url: '/tasks/:id' }] as const

export function deleteTaskMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteTaskMutationKey()
  return mutationOptions<DeleteTaskStatus200, ResponseErrorConfig<Error>, DeleteTaskOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteTask({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir tarefa
 * {@link /tasks/:id}
 */
export function useDeleteTask<TContext>(options: {
  mutation?: UseMutationOptions<DeleteTaskStatus200, ResponseErrorConfig<Error>, DeleteTaskOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteTaskMutationKey()

  const baseOptions = deleteTaskMutationOptions(config) as UseMutationOptions<DeleteTaskStatus200, ResponseErrorConfig<Error>, DeleteTaskOptions, TContext>

  return useMutation<DeleteTaskStatus200, ResponseErrorConfig<Error>, DeleteTaskOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteTaskStatus200, ResponseErrorConfig<Error>, DeleteTaskOptions, TContext>
}