/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteDocumentOptions, DeleteDocumentStatus200 } from '../types/DeleteDocument'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteDocument } from '../clients/deleteDocument'

export const deleteDocumentMutationKey = () => [{ url: '/documents/:id' }] as const

export function deleteDocumentMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteDocumentMutationKey()
  return mutationOptions<DeleteDocumentStatus200, ResponseErrorConfig<Error>, DeleteDocumentOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteDocument({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir documento
 * {@link /documents/:id}
 */
export function useDeleteDocument<TContext>(options: {
  mutation?: UseMutationOptions<DeleteDocumentStatus200, ResponseErrorConfig<Error>, DeleteDocumentOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteDocumentMutationKey()

  const baseOptions = deleteDocumentMutationOptions(config) as UseMutationOptions<DeleteDocumentStatus200, ResponseErrorConfig<Error>, DeleteDocumentOptions, TContext>

  return useMutation<DeleteDocumentStatus200, ResponseErrorConfig<Error>, DeleteDocumentOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteDocumentStatus200, ResponseErrorConfig<Error>, DeleteDocumentOptions, TContext>
}