/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteProcessOptions, DeleteProcessStatus200 } from '../types/DeleteProcess'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteProcess } from '../clients/deleteProcess'

export const deleteProcessMutationKey = () => [{ url: '/processes/:id' }] as const

export function deleteProcessMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteProcessMutationKey()
  return mutationOptions<DeleteProcessStatus200, ResponseErrorConfig<Error>, DeleteProcessOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteProcess({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir processo
 * {@link /processes/:id}
 */
export function useDeleteProcess<TContext>(options: {
  mutation?: UseMutationOptions<DeleteProcessStatus200, ResponseErrorConfig<Error>, DeleteProcessOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteProcessMutationKey()

  const baseOptions = deleteProcessMutationOptions(config) as UseMutationOptions<DeleteProcessStatus200, ResponseErrorConfig<Error>, DeleteProcessOptions, TContext>

  return useMutation<DeleteProcessStatus200, ResponseErrorConfig<Error>, DeleteProcessOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteProcessStatus200, ResponseErrorConfig<Error>, DeleteProcessOptions, TContext>
}