/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DownloadDocumentOptions, DownloadDocumentStatus200 } from '../types/DownloadDocument'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { downloadDocument } from '../clients/downloadDocument'

export const downloadDocumentQueryKey = ({ path }: Omit<DownloadDocumentOptions, 'headers'>) => [{ url: '/documents/:id/download', params: path }] as const

type DownloadDocumentQueryKey = ReturnType<typeof downloadDocumentQueryKey>

export function downloadDocumentQueryOptions({ path }: DownloadDocumentOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = downloadDocumentQueryKey({ path })
  return queryOptions<DownloadDocumentStatus200, ResponseErrorConfig<Error>, DownloadDocumentStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await downloadDocument({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Baixar documento
 * {@link /documents/:id/download}
 */
export function useDownloadDocument<TData = DownloadDocumentStatus200, TQueryData = DownloadDocumentStatus200, TQueryKey extends QueryKey = DownloadDocumentQueryKey>({ path }: { path: DownloadDocumentOptions['path'] | (() => DownloadDocumentOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<DownloadDocumentStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? downloadDocumentQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...downloadDocumentQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}