/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteIntakeOptions, DeleteIntakeStatus200 } from '../types/DeleteIntake'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteIntake } from '../clients/deleteIntake'

export const deleteIntakeMutationKey = () => [{ url: '/intakes/:id' }] as const

export function deleteIntakeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteIntakeMutationKey()
  return mutationOptions<DeleteIntakeStatus200, ResponseErrorConfig<Error>, DeleteIntakeOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteIntake({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Excluir atendimento
 * {@link /intakes/:id}
 */
export function useDeleteIntake<TContext>(options: {
  mutation?: UseMutationOptions<DeleteIntakeStatus200, ResponseErrorConfig<Error>, DeleteIntakeOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteIntakeMutationKey()

  const baseOptions = deleteIntakeMutationOptions(config) as UseMutationOptions<DeleteIntakeStatus200, ResponseErrorConfig<Error>, DeleteIntakeOptions, TContext>

  return useMutation<DeleteIntakeStatus200, ResponseErrorConfig<Error>, DeleteIntakeOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteIntakeStatus200, ResponseErrorConfig<Error>, DeleteIntakeOptions, TContext>
}