/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetHealthStatus200 } from '../types/GetHealth'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getHealth } from '../clients/getHealth'

export const getHealthQueryKey = () => [{ url: '/health' }] as const

type GetHealthQueryKey = ReturnType<typeof getHealthQueryKey>

export function getHealthQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getHealthQueryKey()
  return queryOptions<GetHealthStatus200, ResponseErrorConfig<Error>, GetHealthStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getHealth({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * {@link /health}
 */
export function useGetHealth<TData = GetHealthStatus200, TQueryData = GetHealthStatus200, TQueryKey extends QueryKey = GetHealthQueryKey>(options: {
  query?: Partial<QueryObserverOptions<GetHealthStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getHealthQueryKey()

  const queryResult = useQuery({
   ...getHealthQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}