/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMeStatus200 } from '../types/GetMe'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getMe } from '../clients/getMe'

export const getMeQueryKey = () => [{ url: '/auth/me' }] as const

type GetMeQueryKey = ReturnType<typeof getMeQueryKey>

export function getMeQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMeQueryKey()
  return queryOptions<GetMeStatus200, ResponseErrorConfig<Error>, GetMeStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getMe({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar usuário autenticado
 * {@link /auth/me}
 */
export function useGetMe<TData = GetMeStatus200, TQueryData = GetMeStatus200, TQueryKey extends QueryKey = GetMeQueryKey>(options: {
  query?: Partial<QueryObserverOptions<GetMeStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getMeQueryKey()

  const queryResult = useQuery({
   ...getMeQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}