/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOpenapiJsonStatus200 } from '../types/GetOpenapiJson'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getOpenapiJson } from '../clients/getOpenapiJson'

export const getOpenapiJsonQueryKey = () => [{ url: '/openapi.json' }] as const

type GetOpenapiJsonQueryKey = ReturnType<typeof getOpenapiJsonQueryKey>

export function getOpenapiJsonQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOpenapiJsonQueryKey()
  return queryOptions<GetOpenapiJsonStatus200, ResponseErrorConfig<Error>, GetOpenapiJsonStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getOpenapiJson({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * {@link /openapi.json}
 */
export function useGetOpenapiJson<TData = GetOpenapiJsonStatus200, TQueryData = GetOpenapiJsonStatus200, TQueryKey extends QueryKey = GetOpenapiJsonQueryKey>(options: {
  query?: Partial<QueryObserverOptions<GetOpenapiJsonStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getOpenapiJsonQueryKey()

  const queryResult = useQuery({
   ...getOpenapiJsonQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}