/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetProcessOptions, GetProcessStatus200 } from '../types/GetProcess'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getProcess } from '../clients/getProcess'

export const getProcessQueryKey = ({ path }: Omit<GetProcessOptions, 'headers'>) => [{ url: '/processes/:id', params: path }] as const

type GetProcessQueryKey = ReturnType<typeof getProcessQueryKey>

export function getProcessQueryOptions({ path }: GetProcessOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getProcessQueryKey({ path })
  return queryOptions<GetProcessStatus200, ResponseErrorConfig<Error>, GetProcessStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getProcess({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar processo
 * {@link /processes/:id}
 */
export function useGetProcess<TData = GetProcessStatus200, TQueryData = GetProcessStatus200, TQueryKey extends QueryKey = GetProcessQueryKey>({ path }: { path: GetProcessOptions['path'] | (() => GetProcessOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<GetProcessStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? getProcessQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...getProcessQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}