/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetCompanyOptions, GetCompanyStatus200 } from '../types/GetCompany'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getCompany } from '../clients/getCompany'

export const getCompanyQueryKey = ({ path }: Omit<GetCompanyOptions, 'headers'>) => [{ url: '/companies/:id', params: path }] as const

type GetCompanyQueryKey = ReturnType<typeof getCompanyQueryKey>

export function getCompanyQueryOptions({ path }: GetCompanyOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCompanyQueryKey({ path })
  return queryOptions<GetCompanyStatus200, ResponseErrorConfig<Error>, GetCompanyStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getCompany({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar empresa
 * {@link /companies/:id}
 */
export function useGetCompany<TData = GetCompanyStatus200, TQueryData = GetCompanyStatus200, TQueryKey extends QueryKey = GetCompanyQueryKey>({ path }: { path: GetCompanyOptions['path'] | (() => GetCompanyOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<GetCompanyStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? getCompanyQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...getCompanyQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}