/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetTemplateOptions, GetTemplateStatus200 } from '../types/GetTemplate'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getTemplate } from '../clients/getTemplate'

export const getTemplateQueryKey = ({ path }: Omit<GetTemplateOptions, 'headers'>) => [{ url: '/templates/:id', params: path }] as const

type GetTemplateQueryKey = ReturnType<typeof getTemplateQueryKey>

export function getTemplateQueryOptions({ path }: GetTemplateOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getTemplateQueryKey({ path })
  return queryOptions<GetTemplateStatus200, ResponseErrorConfig<Error>, GetTemplateStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getTemplate({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar modelo de documento
 * {@link /templates/:id}
 */
export function useGetTemplate<TData = GetTemplateStatus200, TQueryData = GetTemplateStatus200, TQueryKey extends QueryKey = GetTemplateQueryKey>({ path }: { path: GetTemplateOptions['path'] | (() => GetTemplateOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<GetTemplateStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? getTemplateQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...getTemplateQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}