/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetPublicPreviewOptions, GetPublicPreviewStatus200 } from '../types/GetPublicPreview'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getPublicPreview } from '../clients/getPublicPreview'

export const getPublicPreviewQueryKey = ({ query }: Omit<GetPublicPreviewOptions, 'headers'>) => [{ url: '/public/preview' }, ...(query ? [query] : [])] as const

type GetPublicPreviewQueryKey = ReturnType<typeof getPublicPreviewQueryKey>

export function getPublicPreviewQueryOptions({ query }: GetPublicPreviewOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getPublicPreviewQueryKey({ query })
  return queryOptions<GetPublicPreviewStatus200, ResponseErrorConfig<Error>, GetPublicPreviewStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getPublicPreview({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar um documento compartilhado publicamente
 * {@link /public/preview}
 */
export function useGetPublicPreview<TData = GetPublicPreviewStatus200, TQueryData = GetPublicPreviewStatus200, TQueryKey extends QueryKey = GetPublicPreviewQueryKey>({ query }: { query: GetPublicPreviewOptions['query'] | (() => GetPublicPreviewOptions['query']) }, options: {
  query?: Partial<QueryObserverOptions<GetPublicPreviewStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { query: typeof query === 'function' ? query() : query }
  const queryKey = resolvedOptions?.queryKey ?? getPublicPreviewQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...getPublicPreviewQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}