/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetClientOptions, GetClientStatus200 } from '../types/GetClient'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getClient } from '../clients/getClient'

export const getClientQueryKey = ({ path }: Omit<GetClientOptions, 'headers'>) => [{ url: '/clients/:id', params: path }] as const

type GetClientQueryKey = ReturnType<typeof getClientQueryKey>

export function getClientQueryOptions({ path }: GetClientOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getClientQueryKey({ path })
  return queryOptions<GetClientStatus200, ResponseErrorConfig<Error>, GetClientStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getClient({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Buscar cliente
 * {@link /clients/:id}
 */
export function useGetClient<TData = GetClientStatus200, TQueryData = GetClientStatus200, TQueryKey extends QueryKey = GetClientQueryKey>({ path }: { path: GetClientOptions['path'] | (() => GetClientOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<GetClientStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? getClientQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...getClientQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}