/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListTasksStatus200 } from '../types/ListTasks'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listTasks } from '../clients/listTasks'

export const listTasksQueryKey = () => [{ url: '/tasks' }] as const

type ListTasksQueryKey = ReturnType<typeof listTasksQueryKey>

export function listTasksQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTasksQueryKey()
  return queryOptions<ListTasksStatus200, ResponseErrorConfig<Error>, ListTasksStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTasks({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar tarefas do usuário logado
 * {@link /tasks}
 */
export function useListTasks<TData = ListTasksStatus200, TQueryData = ListTasksStatus200, TQueryKey extends QueryKey = ListTasksQueryKey>(options: {
  query?: Partial<QueryObserverOptions<ListTasksStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listTasksQueryKey()

  const queryResult = useQuery({
   ...listTasksQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}