/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListCompaniesOptions, ListCompaniesStatus200 } from '../types/ListCompanies'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listCompanies } from '../clients/listCompanies'

export const listCompaniesQueryKey = ({ path }: Omit<ListCompaniesOptions, 'headers'>) => [{ url: '/clients/:clientId/companies', params: path }] as const

type ListCompaniesQueryKey = ReturnType<typeof listCompaniesQueryKey>

export function listCompaniesQueryOptions({ path }: ListCompaniesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listCompaniesQueryKey({ path })
  return queryOptions<ListCompaniesStatus200, ResponseErrorConfig<Error>, ListCompaniesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listCompanies({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar empresas representadas pelo cliente
 * {@link /clients/:clientId/companies}
 */
export function useListCompanies<TData = ListCompaniesStatus200, TQueryData = ListCompaniesStatus200, TQueryKey extends QueryKey = ListCompaniesQueryKey>({ path }: { path: ListCompaniesOptions['path'] | (() => ListCompaniesOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<ListCompaniesStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? listCompaniesQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listCompaniesQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}