/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListUsersStatus200 } from '../types/ListUsers'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listUsers } from '../clients/listUsers'

export const listUsersQueryKey = () => [{ url: '/users' }] as const

type ListUsersQueryKey = ReturnType<typeof listUsersQueryKey>

export function listUsersQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listUsersQueryKey()
  return queryOptions<ListUsersStatus200, ResponseErrorConfig<Error>, ListUsersStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listUsers({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar usuários
 * {@link /users}
 */
export function useListUsers<TData = ListUsersStatus200, TQueryData = ListUsersStatus200, TQueryKey extends QueryKey = ListUsersQueryKey>(options: {
  query?: Partial<QueryObserverOptions<ListUsersStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listUsersQueryKey()

  const queryResult = useQuery({
   ...listUsersQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}