/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListClientsOptions, ListClientsStatus200 } from '../types/ListClients'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listClients } from '../clients/listClients'

export const listClientsQueryKey = ({ query }: Omit<ListClientsOptions, 'headers'> = {}) => [{ url: '/clients' }, ...(query ? [query] : [])] as const

type ListClientsQueryKey = ReturnType<typeof listClientsQueryKey>

export function listClientsQueryOptions({ query }: ListClientsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listClientsQueryKey({ query })
  return queryOptions<ListClientsStatus200, ResponseErrorConfig<Error>, ListClientsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listClients({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar clientes
 * {@link /clients}
 */
export function useListClients<TData = ListClientsStatus200, TQueryData = ListClientsStatus200, TQueryKey extends QueryKey = ListClientsQueryKey>({ query }: { query?: ListClientsOptions['query'] | (() => ListClientsOptions['query']) } = {}, options: {
  query?: Partial<QueryObserverOptions<ListClientsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { query: typeof query === 'function' ? query() : query }
  const queryKey = resolvedOptions?.queryKey ?? listClientsQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listClientsQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}