/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListProcessMovementsOptions, ListProcessMovementsStatus200 } from '../types/ListProcessMovements'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listProcessMovements } from '../clients/listProcessMovements'

export const listProcessMovementsQueryKey = ({ path }: Omit<ListProcessMovementsOptions, 'headers'>) => [{ url: '/processes/:processId/movements', params: path }] as const

type ListProcessMovementsQueryKey = ReturnType<typeof listProcessMovementsQueryKey>

export function listProcessMovementsQueryOptions({ path }: ListProcessMovementsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listProcessMovementsQueryKey({ path })
  return queryOptions<ListProcessMovementsStatus200, ResponseErrorConfig<Error>, ListProcessMovementsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listProcessMovements({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar movimentações do processo
 * {@link /processes/:processId/movements}
 */
export function useListProcessMovements<TData = ListProcessMovementsStatus200, TQueryData = ListProcessMovementsStatus200, TQueryKey extends QueryKey = ListProcessMovementsQueryKey>({ path }: { path: ListProcessMovementsOptions['path'] | (() => ListProcessMovementsOptions['path']) }, options: {
  query?: Partial<QueryObserverOptions<ListProcessMovementsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path }
  const queryKey = resolvedOptions?.queryKey ?? listProcessMovementsQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listProcessMovementsQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}