/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListIntakesOptions, ListIntakesStatus200 } from '../types/ListIntakes'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listIntakes } from '../clients/listIntakes'

export const listIntakesQueryKey = ({ path, query }: Omit<ListIntakesOptions, 'headers'>) => [{ url: '/clients/:clientId/intakes', params: path }, ...(query ? [query] : [])] as const

type ListIntakesQueryKey = ReturnType<typeof listIntakesQueryKey>

export function listIntakesQueryOptions({ path, query }: ListIntakesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listIntakesQueryKey({ path, query })
  return queryOptions<ListIntakesStatus200, ResponseErrorConfig<Error>, ListIntakesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listIntakes({ ...config, path, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar atendimentos do cliente
 * {@link /clients/:clientId/intakes}
 */
export function useListIntakes<TData = ListIntakesStatus200, TQueryData = ListIntakesStatus200, TQueryKey extends QueryKey = ListIntakesQueryKey>({ path, query }: { path: ListIntakesOptions['path'] | (() => ListIntakesOptions['path']); query?: ListIntakesOptions['query'] | (() => ListIntakesOptions['query']) }, options: {
  query?: Partial<QueryObserverOptions<ListIntakesStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { path: typeof path === 'function' ? path() : path, query: typeof query === 'function' ? query() : query }
  const queryKey = resolvedOptions?.queryKey ?? listIntakesQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listIntakesQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}