/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListTemplatesStatus200 } from '../types/ListTemplates'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listTemplates } from '../clients/listTemplates'

export const listTemplatesQueryKey = () => [{ url: '/templates' }] as const

type ListTemplatesQueryKey = ReturnType<typeof listTemplatesQueryKey>

export function listTemplatesQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTemplatesQueryKey()
  return queryOptions<ListTemplatesStatus200, ResponseErrorConfig<Error>, ListTemplatesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTemplates({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar modelos de documento
 * {@link /templates}
 */
export function useListTemplates<TData = ListTemplatesStatus200, TQueryData = ListTemplatesStatus200, TQueryKey extends QueryKey = ListTemplatesQueryKey>(options: {
  query?: Partial<QueryObserverOptions<ListTemplatesStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listTemplatesQueryKey()

  const queryResult = useQuery({
   ...listTemplatesQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}