/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListProcessesOptions, ListProcessesStatus200 } from '../types/ListProcesses'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listProcesses } from '../clients/listProcesses'

export const listProcessesQueryKey = ({ query }: Omit<ListProcessesOptions, 'headers'> = {}) => [{ url: '/processes' }, ...(query ? [query] : [])] as const

type ListProcessesQueryKey = ReturnType<typeof listProcessesQueryKey>

export function listProcessesQueryOptions({ query }: ListProcessesOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listProcessesQueryKey({ query })
  return queryOptions<ListProcessesStatus200, ResponseErrorConfig<Error>, ListProcessesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listProcesses({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar processos
 * {@link /processes}
 */
export function useListProcesses<TData = ListProcessesStatus200, TQueryData = ListProcessesStatus200, TQueryKey extends QueryKey = ListProcessesQueryKey>({ query }: { query?: ListProcessesOptions['query'] | (() => ListProcessesOptions['query']) } = {}, options: {
  query?: Partial<QueryObserverOptions<ListProcessesStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { query: typeof query === 'function' ? query() : query }
  const queryKey = resolvedOptions?.queryKey ?? listProcessesQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listProcessesQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}