/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListEventsOptions, ListEventsStatus200 } from '../types/ListEvents'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listEvents } from '../clients/listEvents'

export const listEventsQueryKey = ({ query }: Omit<ListEventsOptions, 'headers'>) => [{ url: '/events' }, ...(query ? [query] : [])] as const

type ListEventsQueryKey = ReturnType<typeof listEventsQueryKey>

export function listEventsQueryOptions({ query }: ListEventsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listEventsQueryKey({ query })
  return queryOptions<ListEventsStatus200, ResponseErrorConfig<Error>, ListEventsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listEvents({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}

/**
 * @summary Listar eventos visíveis para o usuário logado
 * {@link /events}
 */
export function useListEvents<TData = ListEventsStatus200, TQueryData = ListEventsStatus200, TQueryKey extends QueryKey = ListEventsQueryKey>({ query }: { query: ListEventsOptions['query'] | (() => ListEventsOptions['query']) }, options: {
  query?: Partial<QueryObserverOptions<ListEventsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const resolvedParams = { query: typeof query === 'function' ? query() : query }
  const queryKey = resolvedOptions?.queryKey ?? listEventsQueryKey(resolvedParams)

  const queryResult = useQuery({
   ...listEventsQueryOptions(resolvedParams, config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}