/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { MoveTaskOptions, MoveTaskStatus200 } from '../types/MoveTask'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { moveTask } from '../clients/moveTask'

export const moveTaskMutationKey = () => [{ url: '/tasks/:id/move' }] as const

export function moveTaskMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = moveTaskMutationKey()
  return mutationOptions<MoveTaskStatus200, ResponseErrorConfig<Error>, MoveTaskOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await moveTask({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Mover tarefa entre colunas e reordenar
 * {@link /tasks/:id/move}
 */
export function useMoveTask<TContext>(options: {
  mutation?: UseMutationOptions<MoveTaskStatus200, ResponseErrorConfig<Error>, MoveTaskOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? moveTaskMutationKey()

  const baseOptions = moveTaskMutationOptions(config) as UseMutationOptions<MoveTaskStatus200, ResponseErrorConfig<Error>, MoveTaskOptions, TContext>

  return useMutation<MoveTaskStatus200, ResponseErrorConfig<Error>, MoveTaskOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<MoveTaskStatus200, ResponseErrorConfig<Error>, MoveTaskOptions, TContext>
}