/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SendIntakeEmailOptions, SendIntakeEmailStatus200 } from '../types/SendIntakeEmail'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { sendIntakeEmail } from '../clients/sendIntakeEmail'

export const sendIntakeEmailMutationKey = () => [{ url: '/intakes/:id/send' }] as const

export function sendIntakeEmailMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = sendIntakeEmailMutationKey()
  return mutationOptions<SendIntakeEmailStatus200, ResponseErrorConfig<Error>, SendIntakeEmailOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await sendIntakeEmail({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Enviar a ficha do atendimento por e-mail ao cliente
 * {@link /intakes/:id/send}
 */
export function useSendIntakeEmail<TContext>(options: {
  mutation?: UseMutationOptions<SendIntakeEmailStatus200, ResponseErrorConfig<Error>, SendIntakeEmailOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? sendIntakeEmailMutationKey()

  const baseOptions = sendIntakeEmailMutationOptions(config) as UseMutationOptions<SendIntakeEmailStatus200, ResponseErrorConfig<Error>, SendIntakeEmailOptions, TContext>

  return useMutation<SendIntakeEmailStatus200, ResponseErrorConfig<Error>, SendIntakeEmailOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SendIntakeEmailStatus200, ResponseErrorConfig<Error>, SendIntakeEmailOptions, TContext>
}