/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SignOutStatus200 } from '../types/SignOut'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { signOut } from '../clients/signOut'

export const signOutMutationKey = () => [{ url: '/auth/sign-out' }] as const

export function signOutMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = signOutMutationKey()
  return mutationOptions<SignOutStatus200, ResponseErrorConfig<Error>, undefined, TContext>({
    mutationKey,
    mutationFn: async(_) => {
      const { data } = await signOut({ ...config, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Sair do sistema
 * {@link /auth/sign-out}
 */
export function useSignOut<TContext>(options: {
  mutation?: UseMutationOptions<SignOutStatus200, ResponseErrorConfig<Error>, undefined, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? signOutMutationKey()

  const baseOptions = signOutMutationOptions(config) as UseMutationOptions<SignOutStatus200, ResponseErrorConfig<Error>, undefined, TContext>

  return useMutation<SignOutStatus200, ResponseErrorConfig<Error>, undefined, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SignOutStatus200, ResponseErrorConfig<Error>, undefined, TContext>
}