/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateIntakeOptions, UpdateIntakeStatus200 } from '../types/UpdateIntake'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateIntake } from '../clients/updateIntake'

export const updateIntakeMutationKey = () => [{ url: '/intakes/:id' }] as const

export function updateIntakeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateIntakeMutationKey()
  return mutationOptions<UpdateIntakeStatus200, ResponseErrorConfig<Error>, UpdateIntakeOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateIntake({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar atendimento
 * {@link /intakes/:id}
 */
export function useUpdateIntake<TContext>(options: {
  mutation?: UseMutationOptions<UpdateIntakeStatus200, ResponseErrorConfig<Error>, UpdateIntakeOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateIntakeMutationKey()

  const baseOptions = updateIntakeMutationOptions(config) as UseMutationOptions<UpdateIntakeStatus200, ResponseErrorConfig<Error>, UpdateIntakeOptions, TContext>

  return useMutation<UpdateIntakeStatus200, ResponseErrorConfig<Error>, UpdateIntakeOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateIntakeStatus200, ResponseErrorConfig<Error>, UpdateIntakeOptions, TContext>
}