/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateClientOptions, UpdateClientStatus200 } from '../types/UpdateClient'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateClient } from '../clients/updateClient'

export const updateClientMutationKey = () => [{ url: '/clients/:id' }] as const

export function updateClientMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateClientMutationKey()
  return mutationOptions<UpdateClientStatus200, ResponseErrorConfig<Error>, UpdateClientOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateClient({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar cliente
 * {@link /clients/:id}
 */
export function useUpdateClient<TContext>(options: {
  mutation?: UseMutationOptions<UpdateClientStatus200, ResponseErrorConfig<Error>, UpdateClientOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateClientMutationKey()

  const baseOptions = updateClientMutationOptions(config) as UseMutationOptions<UpdateClientStatus200, ResponseErrorConfig<Error>, UpdateClientOptions, TContext>

  return useMutation<UpdateClientStatus200, ResponseErrorConfig<Error>, UpdateClientOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateClientStatus200, ResponseErrorConfig<Error>, UpdateClientOptions, TContext>
}