/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UploadDocumentOptions, UploadDocumentStatus201 } from '../types/UploadDocument'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { uploadDocument } from '../clients/uploadDocument'

export const uploadDocumentMutationKey = () => [{ url: '/clients/:clientId/documents' }] as const

export function uploadDocumentMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = uploadDocumentMutationKey()
  return mutationOptions<UploadDocumentStatus201, ResponseErrorConfig<Error>, UploadDocumentOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await uploadDocument({ ...config, path, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Enviar documento
 * {@link /clients/:clientId/documents}
 */
export function useUploadDocument<TContext>(options: {
  mutation?: UseMutationOptions<UploadDocumentStatus201, ResponseErrorConfig<Error>, UploadDocumentOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? uploadDocumentMutationKey()

  const baseOptions = uploadDocumentMutationOptions(config) as UseMutationOptions<UploadDocumentStatus201, ResponseErrorConfig<Error>, UploadDocumentOptions, TContext>

  return useMutation<UploadDocumentStatus201, ResponseErrorConfig<Error>, UploadDocumentOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UploadDocumentStatus201, ResponseErrorConfig<Error>, UploadDocumentOptions, TContext>
}