/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateEventOptions, UpdateEventStatus200 } from '../types/UpdateEvent'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateEvent } from '../clients/updateEvent'

export const updateEventMutationKey = () => [{ url: '/events/:id' }] as const

export function updateEventMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateEventMutationKey()
  return mutationOptions<UpdateEventStatus200, ResponseErrorConfig<Error>, UpdateEventOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateEvent({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar evento
 * {@link /events/:id}
 */
export function useUpdateEvent<TContext>(options: {
  mutation?: UseMutationOptions<UpdateEventStatus200, ResponseErrorConfig<Error>, UpdateEventOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateEventMutationKey()

  const baseOptions = updateEventMutationOptions(config) as UseMutationOptions<UpdateEventStatus200, ResponseErrorConfig<Error>, UpdateEventOptions, TContext>

  return useMutation<UpdateEventStatus200, ResponseErrorConfig<Error>, UpdateEventOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateEventStatus200, ResponseErrorConfig<Error>, UpdateEventOptions, TContext>
}