/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateCompanyOptions, UpdateCompanyStatus200 } from '../types/UpdateCompany'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateCompany } from '../clients/updateCompany'

export const updateCompanyMutationKey = () => [{ url: '/companies/:id' }] as const

export function updateCompanyMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateCompanyMutationKey()
  return mutationOptions<UpdateCompanyStatus200, ResponseErrorConfig<Error>, UpdateCompanyOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateCompany({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar empresa
 * {@link /companies/:id}
 */
export function useUpdateCompany<TContext>(options: {
  mutation?: UseMutationOptions<UpdateCompanyStatus200, ResponseErrorConfig<Error>, UpdateCompanyOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateCompanyMutationKey()

  const baseOptions = updateCompanyMutationOptions(config) as UseMutationOptions<UpdateCompanyStatus200, ResponseErrorConfig<Error>, UpdateCompanyOptions, TContext>

  return useMutation<UpdateCompanyStatus200, ResponseErrorConfig<Error>, UpdateCompanyOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateCompanyStatus200, ResponseErrorConfig<Error>, UpdateCompanyOptions, TContext>
}