/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateProcessOptions, UpdateProcessStatus200 } from '../types/UpdateProcess'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateProcess } from '../clients/updateProcess'

export const updateProcessMutationKey = () => [{ url: '/processes/:id' }] as const

export function updateProcessMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateProcessMutationKey()
  return mutationOptions<UpdateProcessStatus200, ResponseErrorConfig<Error>, UpdateProcessOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateProcess({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar processo
 * {@link /processes/:id}
 */
export function useUpdateProcess<TContext>(options: {
  mutation?: UseMutationOptions<UpdateProcessStatus200, ResponseErrorConfig<Error>, UpdateProcessOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateProcessMutationKey()

  const baseOptions = updateProcessMutationOptions(config) as UseMutationOptions<UpdateProcessStatus200, ResponseErrorConfig<Error>, UpdateProcessOptions, TContext>

  return useMutation<UpdateProcessStatus200, ResponseErrorConfig<Error>, UpdateProcessOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateProcessStatus200, ResponseErrorConfig<Error>, UpdateProcessOptions, TContext>
}