/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateTaskOptions, UpdateTaskStatus200 } from '../types/UpdateTask'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { updateTask } from '../clients/updateTask'

export const updateTaskMutationKey = () => [{ url: '/tasks/:id' }] as const

export function updateTaskMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateTaskMutationKey()
  return mutationOptions<UpdateTaskStatus200, ResponseErrorConfig<Error>, UpdateTaskOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateTask({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}

/**
 * @summary Atualizar tarefa
 * {@link /tasks/:id}
 */
export function useUpdateTask<TContext>(options: {
  mutation?: UseMutationOptions<UpdateTaskStatus200, ResponseErrorConfig<Error>, UpdateTaskOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateTaskMutationKey()

  const baseOptions = updateTaskMutationOptions(config) as UseMutationOptions<UpdateTaskStatus200, ResponseErrorConfig<Error>, UpdateTaskOptions, TContext>

  return useMutation<UpdateTaskStatus200, ResponseErrorConfig<Error>, UpdateTaskOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateTaskStatus200, ResponseErrorConfig<Error>, UpdateTaskOptions, TContext>
}